### ISSUE TITLE
PermissionError: [Errno 13] Permission denied ... win32com\\gen_py\\dicts.dat

### ISSUE THREAD

**Issue by zdenop** [mhammond/pywin32#1140]
I am using pywin32 Version: 221 on windows 10 64 bit with python 3.6.3 64bit.

One of my script crashed with PermissionError when I trie to call Microsoft Excel. Here is traceback:

> Traceback (most recent call last):
>   File "F:\Project-Work\mesacnaZavierka\mesacnaZavierka.py", line 782, in on_naReport_clicked
>     message = zuctovanie.na_report(file_name, fromDate, toDate)
>   File "F:\Project-Work\mesacnaZavierka\libs\zuctovanie.py", line 1507, in na_report
>     improve_spreadsheet(filename, (1, 2))
>   File "F:\Project-Work\mesacnaZavierka\libs\zuctovanie.py", line 1113, in improve_spreadsheet
>     xls = Dispatch('Excel.Application')
>   File "C:\Program Files\Python36\lib\site-packages\win32com\client\__init__.py", line 96, in Dispatch
>     return __WrapDispatch(dispatch, userName, resultCLSID, typeinfo, clsctx=clsctx)
>   File "C:\Program Files\Python36\lib\site-packages\win32com\client\__init__.py", line 37, in __WrapDispatch
>     klass = gencache.GetClassForCLSID(resultCLSID)
>   File "C:\Program Files\Python36\lib\site-packages\win32com\client\gencache.py", line 183, in GetClassForCLSID
>     mod = GetModuleForCLSID(clsid)
>   File "C:\Program Files\Python36\lib\site-packages\win32com\client\gencache.py", line 226, in GetModuleForCLSID
>     mod = GetModuleForTypelib(typelibCLSID, lcid, major, minor)
>   File "C:\Program Files\Python36\lib\site-packages\win32com\client\gencache.py", line 266, in GetModuleForTypelib
>     AddModuleToCache(typelibCLSID, lcid, major, minor)
>   File "C:\Program Files\Python36\lib\site-packages\win32com\client\gencache.py", line 579, in AddModuleToCache
>     _SaveDicts()
>   File "C:\Program Files\Python36\lib\site-packages\win32com\client\gencache.py", line 69, in _SaveDicts
>     f = open(os.path.join(GetGeneratePath(), "dicts.dat"), "wb")
> PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Python36\\lib\\site-packages\\win32com\\gen_py\\dicts.dat'

Of course user can not open for writing any file outside user home directory or temp directory. How to fix it (excluding making writable 'C:\\Program Files\\Python36\\lib\\site-packages\\win32com' for all users)?

**Comment by zspitz** [comment]
I've run into something similar from the PythonWin IDE. Unless I run it in Administrator mode, I can't run the `COM makepy` tool.

**Comment by sschukat** [comment]
The problem arises if the existing directory is used as cache directory, even if the current user has no write access. This could happen if an administrator has used the code which creates the directory and then a standard user wants to create a wrapper. To work around the problem check write right.
See https://github.com/sschukat/pywin32/commit/e735c2d35f88b8e5995f7fed7406536476977252#diff-d781d7453dc77e3509a930471c5f4ff5

**Comment by zspitz** [comment]
@sschukat  I would guess the right solution is to read and write from the ProgramData folder as well -- it doesn't require admin permissions to write to it, and it is intended for settings and data which are not user-specific. Do the generated cache files need to be in `lib\site-packages`, which is by default in a subfolder of Program Files?

**Comment by sschukat** [comment]
@zspitz The subfolder does not have to be ```lib\site-packages``` it could be any place which is defined set to the variable ```win32com.__gen_path__```. 
The ProgramData folder is by default also only writeable for administrators and not users, since the location is shared between users and one user should not influence other users. The best place to write files for a user is ```FOLDERID_LocalAppData``` (see https://msdn.microsoft.com/en-us/library/windows/desktop/dd378457(v=vs.85).aspx) since it is writeable and not roaming (a com cache makes only sense on the PC where the program is installed). 
If you want to share cache files between users the default place would be ```FOLDERID_PublicDocuments```. 
This would be a bigger change in the source.

**Comment by zdenop** [comment]
I think I found better workaround: 
I renamed (delete will work too ;-) ) folder "c:\\Program Files\\Python36\\lib\\site-packages\\win32com\gen_py". In text run when I use (as user) win32com.client cache directory was created in user folder (C:\Users\zdenop\AppData\Local\Temp\gen_py\...)

Only difference I recognized is that I need to use absolute path for filename for files in current directory (before the change using just filename without path worked).
