### ISSUE TITLE
Unable to open password-protected .sdf file using adodbapi

### ISSUE THREAD

**Issue by Nonisiuniis** [mhammond/pywin32#1163]
I have application using SQLServer CE as it's data source. It is using runtime 3.5SP1
My testing setup:

Windows Vista x64 SP2 (same result on Windows 10, using Vista just because installing sql-ce on W10 is already unsupported and has some quirks)
python-3.6.4-amd64
pywin32-222.win-amd64-py3.6
adodbapi 2.6.0.7 installed by pip (looks like pywin32 installer is missing some adodbapi files)

SQLServer CE runtime 3.5 SP1 (bundled with application)
Microsoft SQL Server Compact 3.5 SP1 English
Microsoft SQL Server Compact 3.5 SP1 x64 English
(both need to be installed on x64 machine)
or
SQLServer CE runtime 4.0
Microsoft SQL Server Compact 4.0 x64 ENU
(with 4.0, just the x64 is needed)

Application works without problem and i can browse database using [CompactView](https://sourceforge.net/projects/compactview/)
However trying to open this from python ends with following exception:

```
>>> import adodbapi
>>> conn_str = r"Provider=Microsoft.SQLSERVER.CE.OLEDB.3.5;Data Source=C:\app\db.sdf;Password=123456"
>>> conn = adodbapi.connection(conn_str)
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\adodbapi\adodbapi.py", line 112, in connect
    co.connect(kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\adodbapi\adodbapi.py", line 274, in connect
    self.connector.Open()  # Open the ADO connection
  File "<COMObject ADODB.Connection>", line 3, in Open
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\win32com\client\dynamic.py", line 287, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(*(dispid, LCID, wFlags, retType, argTypes) + args)
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft OLE DB Service Components', 'Multiple-step OLE DB operation generated errors. Check each OLE DB status value, if available. No work was done.', None, 0, -2147217887), None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\adodbapi\adodbapi.py", line 116, in connect
    raise api.OperationalError(e, message)
adodbapi.apibase.OperationalError: (com_error(-2147352567, 'Exception occurred.', (0, 'Microsoft OLE DB Service Components', 'Multiple-step OLE DB operation generated errors. Check each OLE DB status value, if available. No work was done.', None, 0, -2147217887), None), 'Error opening connection to "Provider=Microsoft.SQLSERVER.CE.OLEDB.3.5;Data Source=C:\\app\\db.sdf;Password=123456"')
```
Trying the same without specifying password shows expected error (authentication failed), so it means it tries to open correct file.
```
>>> conn_str = r"Provider=Microsoft.SQLSERVER.CE.OLEDB.3.5;Data Source=C:\app\db.sdf"
>>> conn = adodbapi.connect(conn_str)
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\adodbapi\adodbapi.py", line 112, in connect
    co.connect(kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\adodbapi\adodbapi.py", line 274, in connect
    self.connector.Open()  # Open the ADO connection
  File "<COMObject ADODB.Connection>", line 3, in Open
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\win32com\client\dynamic.py", line 287, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(*(dispid, LCID, wFlags, retType, argTypes) + args)
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft SQL Server Compact OLE DB Provider', 'Authentication failed. [,,,,,]', None, 0, -2147217843), None)
```

Using _Microsoft.SQLSERVER.CE.OLEDB.4.0_ in a connection string (when Runtime 4.0 is installed) raises same error. 

Original application works with any installed runtime.
Decompiling the app shows there is no special work done when setting up the connection:
```
public static IDbConnection GetConnection()
{
  IDbConnection dbConnection = (IDbConnection) new SqlCeConnection();
  dbConnection.ConnectionString = "data source=" + Path.GetDirectoryName(Assembly.GetExecutingAssembly().GetModules()[0].FullyQualifiedName) + "\\db.sdf;password=123456";
  dbConnection.Open();
  return dbConnection;
}
```
Doing things manually without adodbapi just with win32com makes no difference (obviously, it's just what adodbapi does under the hood):
```
>>> import pythoncom
>>> import win32com.client
>>> pythoncom.CoInitialize()
>>> c = win32com.client.Dispatch('ADODB.Connection')
>>> c.ConnectionString = conn_str
>>> c.Open()
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "<COMObject ADODB.Connection>", line 3, in Open
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\lib\site-packages\win32com\client\dynamic.py", line 287, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(*(dispid, LCID, wFlags, retType, argTypes) + args)
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft OLE DB Service Components', 'Multiple-step OLE DB operation generated errors. Check each OLE DB status value, if available. No work was done.', None, 0, -2147217887), None)
```

Any ideas?

**Comment by ErikEJ** [comment]
You must change the connection string (Password keyword):

    conn_str = r"Provider=Microsoft.SQLSERVER.CE.OLEDB.3.5;Data Source=C:\app\db.sdf;SSCE:Database Password=123456"

**Comment by Nonisiuniis** [comment]
Ah, the intricate details of "let's make each api accept different parameters". Thank you very much.
