### ISSUE TITLE
error on uninstall/upgrade to version 2.23 - WindowsError: [Error 5] Access is denied

### ISSUE THREAD

**Issue by rudyvogt** [mhammond/pywin32#1173]
Hi,

I am receiving this error, when i upgrade/install from version 2.22 or when you uninstall 2.22 or 2.23
i does not look to be a great issue, because 2.23 seems to work after install

Exception:
Traceback (most recent call last):
  File "c:\program files (x86)\python27\arcgis10.5\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files (x86)\python27\arcgis10.5\lib\site-packages\pip\commands\uninstall.py", line 76, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "c:\program files (x86)\python27\arcgis10.5\lib\site-packages\pip\req\req_set.py", line 347, in uninstall
    req.commit_uninstall()
  File "c:\program files (x86)\python27\arcgis10.5\lib\site-packages\pip\req\req_install.py", line 767, in commit_uninstall
    self.uninstalled.commit()
  File "c:\program files (x86)\python27\arcgis10.5\lib\site-packages\pip\req\req_uninstall.py", line 142, in commit
    rmtree(self.save_dir)
  File "c:\program files (x86)\python27\arcgis10.5\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "c:\program files (x86)\python27\arcgis10.5\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "c:\program files (x86)\python27\arcgis10.5\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "c:\program files (x86)\python27\arcgis10.5\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "c:\program files (x86)\python27\arcgis10.5\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "c:\program files (x86)\python27\arcgis10.5\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "c:\program files (x86)\python27\arcgis10.5\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "c:\program files (x86)\python27\arcgis10.5\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "c:\program files (x86)\python27\arcgis10.5\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "c:\program files (x86)\python27\arcgis10.5\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "c:\program files (x86)\python27\arcgis10.5\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "c:\program files (x86)\python27\arcgis10.5\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "c:\program files (x86)\python27\arcgis10.5\lib\site-packages\pip\utils\__init__.py", line 114, in rmtree_errorhandler
    func(path)
**WindowsError: [Error 5] Access is denied: 'c:\\users\\adm-ru~1\\appdata\\local\\temp\\pip-xpo9a6-uninstall\\program files (x86)\\python27\\arcgis10.5\
\lib\\site-packages\\win32\\win32api.pyd'**

**Comment by mhammond** [comment]
It simply looks like that file is in use - probably by arcgis itself.
