### ISSUE TITLE
AssertionError when reloading pywintypes

### ISSUE THREAD

**Issue by RoscoeReeseHiggings** [mhammond/pywin32#1209]
```python
import pywintypes
import importlib

importlib.reload(pywintypes)
```

produces

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python3\lib\importlib\__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\User\pywintypes.py", line 124, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "C:\Users\User\pywintypes.py", line 117, in __import_pywin32_system_module__
    assert sys.modules[modname] is not old_mod`
```
Can anybody reproduce this error and knows how to fix it?

Originally I come across this when importing pymouse (which uses pywin32) into Robotframework through Custom Libraries, using RED Robot Editor. This Editor apparently imports pywintypes twice, or reloads it during validation, which causes this error. But it can be reproduced just using python as shown above. 

System:
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
pywinversion 223 (installed from a whl file with pip3)
Windows 10 64bit

**Comment by Avasam** [comment]
Closed by https://github.com/mhammond/pywin32/pull/1821
