### ISSUE TITLE
Can't install PIP packages on IronPython 2.7

### ISSUE THREAD

**Issue by DStraniti** [mhammond/pywin32#1226]
Hello,

Any help much appreciated. 

I'm using IronPython 2.7.8 on Window 10. I have several Python versions and distros installed. I am successfully accessing my .NET assemblies from IronPython. Now I need to access some COM assemblies and want to use PyWin32, which has installed fine on normal Python 2.7 on my dev machine.

I found this page detailing how to install packages with PIP: [http://ironpython.net/blog/2014/12/07/pip-in-ironpython-275.html](http://ironpython.net/blog/2014/12/07/pip-in-ironpython-275.html)

PIP didn't work normally, so I assume that the need for -X:Frames is still true for IronPython 2.7.8?

I've tried this on my development PC and a mostly clean PC. I'm using ipy32.exe because my assemblies are 32bit. I did try this with the ipy.exe with the same failed results. My process:

1. Install IronPython 2.7.8
2. From Admin PowerShell, navigate to the IronPython folder: "C:\Program Files\IronPython 2.7"
3. Install PIP: ```ipy32.exe -X:Frames -m ensurepip```
4. Upgrade PIP: ```ipy32.exe -X:Frames -m pip install --upgrade pip```
5. Try installing a package: ```.\ipy.exe -X:Frames -m pip install html5lib```

I tried a few packages including html5lib, which was reported to be working in 2.7.5.

Here are examples with the traceback:

```
PS C:\Program Files\IronPython 2.7> .\ipy.exe -X:Frames -m pip install html5lib
Unhandled exception:
Traceback (most recent call last):
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 187, in run_module
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_vendor\pyparsing.py", line 1261, in setParseAction
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_vendor\pyparsing.py", line 1043, in _trim_arity
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 81, in _run_module_code
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 72, in _run_code
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\__main__.py", line 16, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\__init__.py", line 42, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\cmdoptions.py", line 16, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\index.py", line 24, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\download.py", line 39, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\utils\logging.py", line 9, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\utils\misc.py", line 21, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 77, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_vendor\packaging\requirements.py", line 9, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_vendor\pyparsing.py", line 4734, in <module>
IndexError: index out of range: -1
```

```
PS C:\Program Files\IronPython 2.7> .\ipy.exe -X:Frames -m pip install matplotlib
Unhandled exception:
Traceback (most recent call last):
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 187, in run_module
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_vendor\pyparsing.py", line 1261, in setParseAction
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_vendor\pyparsing.py", line 1043, in _trim_arity
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 81, in _run_module_code
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 72, in _run_code
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\__main__.py", line 16, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\__init__.py", line 42, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\cmdoptions.py", line 16, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\index.py", line 24, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\download.py", line 39, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\utils\logging.py", line 9, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\utils\misc.py", line 21, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 77, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_vendor\packaging\requirements.py", line 9, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_vendor\pyparsing.py", line 4734, in <module>
IndexError: index out of range: -1
```

```
PS C:\Program Files\IronPython 2.7> .\ipy32.exe -X:Frames -m pip install PyWin32
Unhandled exception:
Traceback (most recent call last):
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 187, in run_module
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_vendor\pyparsing.py", line 1261, in setParseAction
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_vendor\pyparsing.py", line 1043, in _trim_arity
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 81, in _run_module_code
  File "C:\Program Files\IronPython 2.7\Lib\runpy.py", line 72, in _run_code
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\__main__.py", line 16, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\__init__.py", line 42, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\cmdoptions.py", line 16, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\index.py", line 24, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\download.py", line 39, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\utils\logging.py", line 9, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\utils\misc.py", line 21, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 77, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_vendor\packaging\requirements.py", line 9, in <module>
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_vendor\pyparsing.py", line 4734, in <module>
IndexError: index out of range: -1
```

**Comment by mhammond** [comment]
I'm afraid you need to talk to the iron python team to work out what is going on.

**Comment by DStraniti** [comment]
My apologies. I meant to submit this to IronPython. I must have gotten my open tabs confused. 

@vernondcole: Thanks for the tips! I hadn't found adodbapi before.

**Comment by DStraniti** [comment]
For those searching PyWin32 about this problem, here is some help (points to a solution):

https://github.com/IronLanguages/ironpython2/issues/382

**Comment by killo3967** [comment]
The error was:

Upgrade PIP: ipy32.exe -X:Frames -m pip install --upgrade pip

Don't upgrade pip from original version, this cause the problem. I dad the same proble and the solution was uninstall Ironpython, delete all directories andd reinstall again

**Comment by vernondcole** [comment]
If I recall correctly (and it has been years since I examined this) there
was a known bug in pip for IronPython.
A report to the project issues board at https://pip.pypa.io/ might be in
order.

**Comment by killo3967** [comment]
I have recently managed to install libraries in Ironpython 2.7 and the procedure is as follows:

1.- Install IronPython 2.7.8
2.- From Admin CMD Shell, navigate to the IronPython folder: "C:\Program Files\IronPython 2.7"
3.- Install PIP: ipy32.exe -X:Frames -m ensurepip
4.-   !!! NEVER !!! Upgrade PIP: ipy32.exe -X:Frames -m pip install --upgrade pip
5.- Try installing a package: ipy.exe -X:Frames -m pip install html5lib -v <== This fails but...

The log is:
C:\Program Files\IronPython 2.7>ipy.exe -X:Frames -m pip install html5lib -v
DEPRECATION: A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Created temporary directory: c:\users\server\appdata\local\temp\pip-ephem-wheel-cache-tpy4_i
Created temporary directory: c:\users\server\appdata\local\temp\pip-req-tracker-wtkycs
Created requirements tracker 'c:\\users\\server\\appdata\\local\\temp\\pip-req-tracker-wtkycs'
Created temporary directory: c:\users\server\appdata\local\temp\pip-install-r1oo1f
Collecting html5lib
  1 location(s) to search for versions of html5lib:
  * https://pypi.org/simple/html5lib/
  Getting page **https://pypi.org/simple/html5lib/**
  Found index url https://pypi.org/simple
  Looking up "https://pypi.org/simple/html5lib/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/html5lib/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/html5lib/
Cleaning up...
Removed build tracker 'c:\\users\\server\\appdata\\local\\temp\\pip-req-tracker-wtkycs'
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\cli\base_command.py", line 188, in main
    status = self.run(options, args)
  File "C:\Program Files\IronPython 2.7\Lib\site-packages\pip\_internal\commands\install.py", line 345, in run
    resolver.resolve(requirement_set).... and cotinue the error

As you could see he tried to install from "https://pypi.org/simple/html5lib/"
Go to this page and 'copy the link' of the last '*py2*.whl' pakage. 
In this case was: html5lib-1.1-py2.py3-none-any.whl
An his url is: https://files.pythonhosted.org/packages/6c/dd/a834df6482147d48e225a49515aabc28974ad5a4ca3215c18a882565b028/html5lib-1.1-py2.py3-none-any.whl#sha256=0d78f8fde1c230e99fe37986a60526d7049ed4bf8a9fadbad5f00e22e58e041d

then try  "ipy.exe -X:Frames -m pip install https://files.pythonhosted.org/packages/6c/dd/a834df6482147d48e225a49515aabc28974ad5a4ca3215c18a882565b028/html5lib-1.1-py2.py3-none-any.whl#sha256=0d78f8fde1c230e99fe37986a60526d7049ed4bf8a9fadbad5f00e22e58e041d"

An then it's could say two things
1.- Finish the installation
2.- Fail because dependencies. And this is the problem. You must install manually al the dependencies of the lib. It's a little work bus at final it works.
