### ISSUE TITLE
Error with installer when finishing

### ISSUE THREAD

**Issue by DragonOsman** [mhammond/pywin32#1292]
I'm trying to install the latest release of Pywin32 2.7 for my Python 2.7.15 on my Windows 10 laptop.  When the installer finished installing Pywin32, I saw these messages printed to the screen:
```
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
```
What's this about?  And is there anything I need to do?

The reason I wanted to install Pywin32 was to get rid of this error:
```
emrun index.html
No module named win32api
Importing Python win32 modules failed! This most likely occurs if you do not have PyWin32 installed! Get it from http://sourceforge.net/projects/pywin32/
Traceback (most recent call last):
  File "C:\emscripten\emrun.py", line 1604, in <module>
    sys.exit(main())
  File "C:\emscripten\emrun.py", line 1597, in main
    returncode = run()
  File "C:\emscripten\emrun.py", line 1459, in run
    browser = find_browser(str(options.browser))
  File "C:\emscripten\emrun.py", line 1020, in find_browser
    return win_get_default_browser()
  File "C:\emscripten\emrun.py", line 1001, in win_get_default_browser
    import_win32api_modules()
  File "C:\emscripten\emrun.py", line 89, in import_win32api_modules
    import win32api
ImportError: No module named win32api
```
I already have a `winpython` directory inside my Python root directory, though.  So how do I fix the error?

**Comment by DragonOsman** [comment]
The error with Emscripten is solved.  I just want to know what the error from the PyWin32 installer is about now.  Thanks in advance for any replies.
