### ISSUE TITLE
No module named win32api

### ISSUE THREAD

**Issue by sryze** [mhammond/pywin32#1307]
Python can't find the  `win32api` module.

* Steps to reproduce the problem.

1. Run python
2. Execute `import win32api`

For example, I'm trying to build [Deluge](https://github.com/deluge-torrent/deluge) on Windows, here is an error that I get when I try to run it:

```
(env) c:\deluge>env\Scripts\deluged
Traceback (most recent call last):
  File "c:\deluge\env\Scripts\deluged-script.py", line 11, in <module>
    load_entry_point('deluge', 'console_scripts', 'deluged')()
  File "c:\deluge\deluge\core\daemon_entry.py", line 90, in start_daemon
    from deluge.core.daemon import is_daemon_running
  File "c:\deluge\deluge\core\daemon.py", line 22, in <module>
    from deluge.core.core import Core
  File "c:\deluge\deluge\core\core.py", line 23, in <module>
    from twisted.web.client import Agent, readBody
  File "c:\deluge\env\lib\site-packages\twisted-18.9.0-py2.7-win32.egg\twisted\web\client.py", line 41, in <module>
    from twisted.internet.endpoints import HostnameEndpoint, wrapClientTLS
  File "c:\deluge\env\lib\site-packages\twisted-18.9.0-py2.7-win32.egg\twisted\internet\endpoints.py", line 41, in <module>
    from twisted.internet.stdio import StandardIO, PipeAddress
  File "c:\deluge\env\lib\site-packages\twisted-18.9.0-py2.7-win32.egg\twisted\internet\stdio.py", line 30, in <module>
    from twisted.internet import _win32stdio
  File "c:\deluge\env\lib\site-packages\twisted-18.9.0-py2.7-win32.egg\twisted\internet\_win32stdio.py", line 9, in <module>
    import win32api
```

```
>pip show pywin32
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Name: pywin32
Version: 224
Summary: Python for Window Extensions
Home-page: https://github.com/mhammond/pywin32
Author: Mark Hammond (et al)
Author-email: mhammond@skippinet.com.au
License: PSF
Location: e:\sources\deluge\env\lib\site-packages\pywin32-224-py2.7-win32.egg
Requires:
Required-by: pypiwin32, deluge
```

* Version of Python and pywin32

  pywin32 224
  Tried with both Python 2.7 and 3.7
  Windows 10

**Comment by JackyNiu** [comment]
You kan see source code ,there only have pass.

**Comment by mhammond** [comment]
You should speak to the deluge people about this, but it appears `e:\sources\deluge\env\lib\site-packages` isn't on your path (note the tracebacks above all refer to `c:\deluge\env\lib\site-packages\`
