### ISSUE TITLE
Having trouble with win32com in python

### ISSUE THREAD

**Issue by antony0808** [mhammond/pywin32#1317]
when i run the command

```
import win32com.client
exl = win32com.client.Dispatch('Excel.Application')
```
im getting the following error.. how can i solve this

```
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221021, 'Operation unavailable', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "C:\Program Files\Python36\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Program Files\Python36\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147024893, 'The system cannot find the path specified.', None, None)
```
![capture](https://user-images.githubusercontent.com/24729050/54012494-40d64a80-419c-11e9-9b1b-fecf4e68a6e1.PNG)

**Comment by mhammond** [comment]
See https://github.com/mhammond/pywin32/blob/master/README.md#support
