### ISSUE TITLE
encoding error

### ISSUE THREAD

**Issue by bgailer** [mhammond/pywin32#1325]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

pywin3.7 build 224 windows 10
* Steps to reproduce the problem.
open a file containing:

<# -*- coding: utf-8 -*-
 ┌  (that's unicode 0x250c>

and try to save it.

* Expected behavior
file is saved

* Actual behavior. Error 
![save_error](https://user-images.githubusercontent.com/1512596/55199259-d65b6d80-518f-11e9-8d1d-8be1222df353.png)

Clicking Yes to "save anyway" results in:
<  File "C:\Python37\Lib\site-packages\pythonwin\pywin\framework\editor\document.py", line 77, in OnSaveDocument
    self.SaveFile(fileName)
  File "C:\Python37\Lib\site-packages\pythonwin\pywin\scintilla\document.py", line 64, in SaveFile
    ok = view.SaveTextFile(fileName, encoding=encoding)
  File "C:\Python37\Lib\site-packages\pythonwin\pywin\scintilla\view.py", line 389, in SaveTextFile
    doc._SaveTextToFile(self, filename, encoding=encoding)
  File "C:\Python37\Lib\site-packages\pythonwin\pywin\scintilla\document.py", line 169, in _SaveTextToFile
    file_contents = s.encode(source_encoding)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u250c' in position 25: ordinal not in range(256)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\Lib\site-packages\pythonwin\pywin\framework\editor\document.py", line 92, in OnSaveDocument
    self.SaveFile(fileName, encoding="latin-1")
  File "C:\Python37\Lib\site-packages\pythonwin\pywin\scintilla\document.py", line 64, in SaveFile
    ok = view.SaveTextFile(fileName, encoding=encoding)
  File "C:\Python37\Lib\site-packages\pythonwin\pywin\scintilla\view.py", line 389, in SaveTextFile
    doc._SaveTextToFile(self, filename, encoding=encoding)
  File "C:\Python37\Lib\site-packages\pythonwin\pywin\scintilla\document.py", line 169, in _SaveTextToFile
    file_contents = s.encode(source_encoding)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u250c' in position 25: ordinal not in range(256)
win32ui.error: OnSaveDocument() virtual handler (<bound method EditorDocumentBase.OnSaveDocument of <pywin.framework.editor.color.coloreditor.SyntEditDocument object at 0x00000242A47CE978>>) raised an exception
>
Trying to open same file on pywin3.6 build 223 windows 10 results in the app terminating.

* Version of Python and pywin32

**Comment by Aareon** [comment]
I'd like to think that the encoding choice here is left over from Python 2.7. I see no problem with changing this to `utf-8`.

**Comment by mhammond** [comment]
There are actually a couple of issues here:

* For some reason, your 'coding' line isn't being used. We should try and work out why that's the case.

* The line you refer to with the hard-coded `latin-1` is a fallback when the chosen encoding can't be used. The intent behind this is to use an encoding that can never fail, and long ago, that's roughly what latin-1 was. Using `utf-8` there isn't correct as files exist which can't be saved as utf-8 and this exact issue will remain. Note that there's a case for making utf-8 the default, but that's not relevant here - we are talking about what to do when the encoding fails.

So I think the correct fix here is to use something like `unicode_escape` as the fallback and to work out why your coding line was being ignored.

Re changing the default, my concern with blindly changing the default to utf-8 is that there's almost certainly people editing non-ascii stuff without a coding line, meaning they are using latin-1. If we change this, these files will not load correctly - so I think we'd need to make it an option in the UI.

**Comment by metolone** [comment]
Re the last comment...according to https://docs.python.org/3/tutorial/interpreter.html#source-code-encoding Python 3 assumes UTF-8 if there is no encoding default, so it would be nice if Pythonwin used the same default.  The #encoding line isn't needed for UTF-8 in Python 3.   

Re this issue...I also am seeing this encoding failure on save in Pythonwin 224.  Pythonwin 221 does not have the issue.  I haven't checked the rest.  I am using Python 3.7 64-bit on Windows 10 64-bit.

**Comment by kxrob** [comment]
Now found this thread after I just posted a patch in #1559 : Should solve both: the file save of non-ascii/latin1 and the PY3 default utf8.

Note: The patch above by Aareon doesn't seem to do the PY3 utf8 default thing at the right place: It would wrongly save only after Error-Dialog as utf8 (not binary) as a last resort when e.g. the given or default encoding doesn't handle it;  when the utf8 (default or explicit) is at work, this should never happen; But when other encoding is explicitely defined and raises error, then it should not go even more easy and false as utf8 and different from advertisement. The user would interrupt most time anyway.
Maybe a file with failing encoding tag should never save at all, not even binary - until the user fixes chars or encoding tag.
