### ISSUE TITLE
(-2147024891, 'Access is denied.', None, None)

### ISSUE THREAD

**Issue by tom-kacvinsky** [mhammond/pywin32#1331]
* Expected behavior and actual behavior.

using Python 2.7.5 for 32-bit Windows, using pywin32 219, we do not see an error loading a COM object.  However, for Python 2.7.14 with pywin32 223, we get the following error message

ERROR: failed to create the foo COM application object.
(-2147024891, 'Access is denied.', None, None)

The interesting thing is that for Python 2.7.14/pywin32 223, if the user switches accounts, the problem goes away.  Given the error above, I suspect pywin32 has become more stringent in terms of checking permissions, either by design or by using a different underlying system library, or perhaps an updated system library.

* Steps to reproduce the problem.

I need to get this information from the field engineer I am working with - it might be complicated as this is proprietary code I am working with.  Are there any variables (within Python or an environment variable) I can set to trace exactly where the error is happening?  If there is, that might help me come up with a reproducer.

* Version of Python and pywin32

Python 2.7.14
pywin32 223

I also need to find out the version of Windows being (7/8/10, is it a server version, etc...)

**Comment by mhammond** [comment]
Thank you for taking this to the mailing list - please reopen if you've identified a bug here (although I can't think of any pywin32 changes which would explain this)

**Comment by umamahesh0123** [comment]
Dear, were you able to fix the problem ? I am facing same problem when I trigger the code from Jenkins, but if I trigger same code from command prompt using batch file, I don't see this problem. Could you please help to fix it. 

Code:
xl=win32com.client.Dispatch("Excel.Application")

**Comment by umamahesh0123** [comment]
Here is more details , when i try to run the above command from jenkins, i am facing below error 

  File "D:\Program Files\Python37\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221021, 'Operation unavailable', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "W:\WAY4DTNA\Jenkins_2_391_1_Repository\SAP20163\workspace\Uma_Test_RF_WAY4Runner_TestCase\exec_3\svn\automation\automation\V2\RobotFramework/Testcases\runtdsgen.py", line 51, in <module>
    runmacro()
  File "W:\WAY4DTNA\Jenkins_2_391_1_Repository\SAP20163\workspace\Uma_Test_RF_WAY4Runner_TestCase\exec_3\svn\automation\automation\V2\RobotFramework/Testcases\runtdsgen.py", line 44, in runmacro
    xl=win32com.client.Dispatch("Excel.Application")
  File "D:\Program Files\Python37\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "D:\Program Files\Python37\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "D:\Program Files\Python37\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147024891, 'Access is denied.', None, None)
