### ISSUE TITLE
IOError: [Errno 9] Bad file descriptor at the end of win32/Demos/pipes/runproc.py

### ISSUE THREAD

**Issue by raczben** [mhammond/pywin32#1405]
[runproc](https://github.com/mhammond/pywin32/blob/d64fac8d7bda2cb1d81e2c9366daf99e802e327f/win32/Demos/pipes/runproc.py) demo code fails with the following message: `IOError: [Errno 9] Bad file descriptor`

**Expected behavior and actual behavior.**
```
> pytohn runproc.py
Read on stdout:  'hmmmmm\r\n'
Read on stderr:  'Blah...'
by
close failed in file object destructor:                  <== HERE IS THE ERROR
IOError: [Errno 9] Bad file descriptor
```

**Steps to reproduce the problem.**
Run the `runproc.py` example.

**Version of Python and pywin32**
 - pywin32==224
 - Python 2.7.16

**Note:**
This file is written in Python-2.x. I recommend to migrate to 3.x. (The 2.x support ends in this year.)

**Comment by Avasam** [comment]
I tried to replicate, but looks like the return type of `win32api.DuplicateHandle` may have changed from `int` to `PyHANDLE` at some point, because the demo now fails on this:
```
Traceback (most recent call last):
  File "e:\Users\Avasam\Documents\Git\pywin32\win32\Demos\pipes\runproc.py", line 112, in <module>
    p.run(exe + " cat.py")
  File "e:\Users\Avasam\Documents\Git\pywin32\win32\Demos\pipes\runproc.py", line 97, in run
    self.stdin = os.fdopen(msvcrt.open_osfhandle(self.hStdin_w, 0), "wb")
TypeError: open_osfhandle() argument 1 must be int, not PyHANDLE
```
