### ISSUE TITLE
Pandas's read.sql fails with adodbapi connection

### ISSUE THREAD

**Issue by ParfaitG** [mhammond/pywin32#1423]
Directly related to this [issue](https://github.com/pandas-dev/pandas/issues/27547), Pandas' `read_sql` cannot generate data frames using an `adodbapi` connection. Pandas maintainers emphasize issue is an `adodbapi` [bug](https://github.com/pandas-dev/pandas/issues/27547#issuecomment-516311930) and not an issue with Pandas. 

Specifically, attempting to import data from an MS Access database using OLEDB provider:

```python
import pandas as pd
import adodbapi

conn = adodbapi.connect(r'Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Path\To\MS\Access\DB.accdb;')

df = pd.read_sql("SELECT TOP 10 * FROM myTable", conn)
print(df)
	
conn.close()

```

Yields the below traceback and error:

```
Traceback (most recent call last):
  File "OleDBConnection.py", line 14, in <module>
    df = pd.read_sql("SELECT TOP 10 * FROM Random_Data", conn)
  File "C:\Users\ParfaitG\AppData\Roaming\Python\Python37\site-packages\pandas\io\sql.py", line 380, in read_sql
    chunksize=chunksize)
  File "C:\Users\ParfaitG\AppData\Roaming\Python\Python37\site-packages\pandas\io\sql.py", line 1482, in read_query
    parse_dates=parse_dates)
  File "C:\Users\ParfaitG\AppData\Roaming\Python\Python37\site-packages\pandas\io\sql.py", line 141, in _wrap_result
    coerce_float=coerce_float)
  File "C:\Users\ParfaitG\AppData\Roaming\Python\Python37\site-packages\pandas\core\frame.py", line 1512, in from_records
    coerce_float=coerce_float)
  File "C:\Users\ParfaitG\AppData\Roaming\Python\Python37\site-packages\pandas\core\internals\construction.py", line 408, in to_arrays
    elif isinstance(data[0], ABCSeries):
  File "C:\Users\ParfaitG\AppData\Roaming\Python\Python37\site-packages\pandas\core\dtypes\generic.py", line 9, in _check
    return getattr(inst, attr, '_typ') in comp
  File "C:\Users\ParfaitG\AppData\Roaming\Python\Python37\site-packages\adodbapi\apibase.py", line 474, in __getattr__
    return self._getValue(self.rows.columnNames[name.lower()])
KeyError: '_typ'
```
Expected result is a Pandas data frame without error. Other DB-APIs, noteably `pyodbc` using ODBC drivers, do not have this issue.

```python
import pandas as pd
import pyodbc

conn = pyodbc.connect(r'DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=C:\Path\To\MS\Access\DB.accdb;')

df = pd.read_sql("SELECT TOP 10 * FROM myTable", conn)
print(df)

conn.close()

```
One contributor [suggested a fix](https://github.com/pandas-dev/pandas/issues/27547#issuecomment-529893793) which does resolve above issue, requiring a change of few lines to the `adodbapi/apibase.py` script. PyWin32 authors can consider this fix  or re-factor code in other ways to resolve this issue. 

Arguably, this is an important issue since OLEDB is a popular Windows data source API and a mainstay in some companies. Various forums including StackOverflow have raised this [Pandas issue](https://stackoverflow.com/questions/56075159/convert-listadodbapi-apibase-sqlrow-to-pd-dataframe),  Additionally, with Pandas being a very popular data analytics library with its facility to connect to backend databases across PEP 249 compliant DB-APIs such a fix of this issue can strengthen the Python ecosystem and serve its community.

**Comment by vernondcole** [comment]
I am working on updating the adodbapi code as we speak. I will include this
in my work.

**Comment by Avasam** [comment]
Fixed by https://github.com/mhammond/pywin32/pull/1475
