### ISSUE TITLE
pythonservice.exe is incompatible with ProactorEventLoop

### ISSUE THREAD

**Issue by sm-Fifteen** [mhammond/pywin32#1452]
Since Python 3.8, ProactorEventLoop is the default event loop for asyncio running on Windows. In most if not all cases, the transition was seamless, except pywin32 services don't seem to work well with it, for some reason. Running the service in debug mode causes no error

```py
import win32serviceutil, win32service, win32event, servicemanager
import socket
import asyncio

def create_proactor_event_loop():
    loop = asyncio.ProactorEventLoop()
    asyncio.set_event_loop(loop)
    print("Event loop OK")

def create_selector_event_loop():
    import selectors
    selector = selectors.SelectSelector()
    loop = asyncio.SelectorEventLoop(selector)
    asyncio.set_event_loop(loop)
    print("Event loop OK")

class AppServerSvc (win32serviceutil.ServiceFramework):
    _svc_name_ = "AsyncioService"
    _svc_display_name_ = "AsyncioService"

    def __init__(self,args):
        win32serviceutil.ServiceFramework.__init__(self,args)
        self.hWaitStop = win32event.CreateEvent(None,0,0,None)
        socket.setdefaulttimeout(60)

    def SvcStop(self):
        self.ReportServiceStatus(win32service.SERVICE_STOP_PENDING)
        win32event.SetEvent(self.hWaitStop)

    def SvcDoRun(self):
        servicemanager.LogMsg(servicemanager.EVENTLOG_INFORMATION_TYPE,
                              servicemanager.PYS_SERVICE_STARTED,
                              (self._svc_name_,''))
        self.main()

    def main(self):
        # On Windows, will create a asyncio.ProactorEventLoop
        # It will then fail with "ValueError: set_wakeup_fd only works in main thread"
        # This is despite the call to set_wakeup_fd having a check that we're on the main thread?
        create_proactor_event_loop()
        # Selector event loop works fine
        create_selector_event_loop()

# Also fails in the exact same way
# if servicemanager.RunningAsService(): asyncio.get_event_loop()

if __name__ == '__main__':
    win32serviceutil.HandleCommandLine(AppServerSvc)
```

```
Python could not import the service's module 
Traceback (most recent call last):
  File "C:\Users\sm-Fifteen\Documents\prog\win32_services_test\service_test_async.py", line 35, in <module>
    asyncio.get_event_loop()
  File "C:\Program Files\Python\Python38\lib\asyncio\events.py", line 636, in get_event_loop
    self.set_event_loop(self.new_event_loop())
  File "C:\Program Files\Python\Python38\lib\asyncio\events.py", line 656, in new_event_loop
    return self._loop_factory()
  File "C:\Program Files\Python\Python38\lib\asyncio\windows_events.py", line 310, in __init__
    super().__init__(proactor)
  File "C:\Program Files\Python\Python38\lib\asyncio\proactor_events.py", line 633, in __init__
    signal.set_wakeup_fd(self_no)
ValueError: set_wakeup_fd only works in main thread 
```

As a workaround, it's possible to manually create a selector event loop (the default in Python 3.7) instead, (see `create_selector_event_loop` above) before calling `asyncio.get_event_loop()`.

### System info

Windows 10 1803
Python 3.8.0
pywin32 227

**Comment by mhammond** [comment]
Thanks for the report, but it's not clear if you are suggesting there's something pywin32 can do here? ie, this seems like something an asyncio based service would need to take into account rather than pywin32 itself?

(Note that debug mode is a bit of a special case, but in non-debug mode it's windows itself which decides what thread is used, so I don't think there's anything we can do to help ensure things are on the "main" thread when running as a real service)

**Comment by sm-Fifteen** [comment]
It's a bit strange, really, if you look at the code the stack trace is referring to:

https://github.com/python/cpython/blob/master/Lib/asyncio/proactor_events.py#L630-L632

...there appears to be a check to see if the running thread is indeed the main thread, and `signal.set_wakeup_fd` running means the check needs to have passed, so it at least seems like the specific way in which pywin32's services end up running cause a deprecancy in how python checks for threads. It might actually be a CPython issue, but I don't know enough about what's going on internally to tell or properly file a report for it.

**Comment by mhammond** [comment]
https://bugs.python.org/issue31517 has some interesting details, and searching for all bugs containing "main_thread" has many hits. Of interest though is that threading.py treats the first thread which imports it as the main thread - so it might be interesting to experiment with importing threading.py in (say) win32serviceutil or similar and see what effect that has.

**Comment by sm-Fifteen** [comment]
> https://bugs.python.org/issue31517 has some interesting details, and searching for all bugs containing "main_thread" has many hits. Of interest though is that threading.py treats the first thread which imports it as the main thread - so it might be interesting to experiment with importing threading.py in (say) win32serviceutil or similar and see what effect that has.

Yeah, that seems to be the issue, `threding` and `signal` have different definitions of "main thread", I've done some experimentation, though, and there doesn't seem to be anywhere I can import `threading` to make `signal` happy. It *looks* like `signal` uses the [`_PyRuntime` global (?) to determine what the main thread is](https://github.com/python/cpython/blob/7483451577916e693af6d20cf520b2cc7e2174d2/Modules/signalmodule.c#L699-L704), which looks to be defined as [the first thread in the process to have called Py_Initialize](https://github.com/python/cpython/blob/080ee5a88406fb68aaab741145cd5d2a7c5f2ad6/Python/pylifecycle.c#L75-L93), and then compares [the current thread ID with what's registered as the interpreter](https://github.com/python/cpython/blob/7483451577916e693af6d20cf520b2cc7e2174d2/Modules/signalmodule.c#L192-L199).

I am *way* in over my head with this, but given how `pythonservice` acts as an embedded Python interpreter, wouldn't that mismatch come from something it's doing wrong in regards to what thread it assumes to be running on? Running [the CPython interpreter as a service directly](https://github.com/mhammond/pywin32/blob/master/win32/Demos/service/nativePipeTestService.py) has the same problem, but if there are some strange thread shenanigans going on, shouldn't `pythonservice` account for them?
