### ISSUE TITLE
Setting connector Cursorlocation on anything other than 2 generates exception when executing queries

### ISSUE THREAD

**Issue by Vesyrak** [mhammond/pywin32#1492]
When I execute a query on a SQL CE 3.5 .sdf file, the opening of the connection works, but queries throw the following exception: 

```
Traceback (most recent call last):
  File "<path>/sdf_parser.py", line 37, in <module>
    print(con.get_table_names())
  File "<path>\.virtualenvs\building-z-obelisk-link-WNSw3mH4\lib\site-packages\adodbapi\adodbapi.py", line 482, in get_table_names
    schema = self.connector.OpenSchema(20) # constant = adSchemaTables
  File "<COMObject ADODB.Connection>", line 2, in OpenSchema
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft SQL Server Compact OLE DB Provider', 'Multiple-step OLE DB operation generated errors. Check each OLE DB status value, if available. No work was done.', None, 0, -2147217887), None)
```
* Expected behavior and actual behavior.
Program is expected to list all table names. Instead, the exception is thrown

* Steps to reproduce the problem.
SQL CE 3.5 .sdf file required as input.
```
import adodbapi as db
constr = """Provider=Microsoft.SQLSERVER.CE.OLEDB.3.5;Data Source=testdb.sdf;"""
con = db.connect(constr)
# Default connect() sets it to 3
# Uncommenting the following line ensures it works again.
# con.connector.CursorLocation=2
```
* Version of Python and pywin32
Python 3.8.1, pywin32 227

**Comment by vernondcole** [comment]
Something in SQL CE appears to not like client-side cursors.
I changed the default years ago, but you can set it back by stepping on the module-level variable. That is by design.
Try something like (working from the top of my head here -- I never understood why it wants the module name twice, but that's what worked for me. -- )
```
import adodbapi as db
import adoconst
db.adodbapi.defaultCursorLocation = adoconst.adUseServer
```
adUseServer is, of course, a complex way of saying "2".

**Comment by vernondcole** [comment]
It must have been at least 10 years ago that I changed the default for the
connection object to use client-side cursors. I no longer remember why.

It is fairly simple to override the default as soon as the module is
imported, but the definitive fix for this problem would be to revert the
default cursor location to server-side.

Does anyone have wisdom to shed on the question of whether this should be
changed (back)?
--
Vernon Cole
