### ISSUE TITLE
"TypeError 'float' object cannot be interpreted as an integer" returned by collectdatafor function (win32pdhquery.py

### ISSUE THREAD

**Issue by grokkingit** [mhammond/pywin32#1549]
Versions:
Python 3.7.4
pywin32 (228)

Basic test of the pdhquery class returns a TypeError from the collectdatafor function:

```python
import win32pdhquery 
from pprint import pprint 

 query = win32pdhquery.Query()
   query.addcounter("Memory", "Available Bytes")
  print("query.paths:")
 pprint(query.paths)
 
 print("\nquery.curresults:")
  query.collectdatafor(4,2)  
  pprint(query.curresults)
```

Output:
```python
query.paths:
['\\Memory\\Available Bytes']

query.curresults:
Traceback (most recent call last):
  File "C:/Users/myuser/PycharmProjects/WinMetrics/venv/PerfMonReader.py", line 16, in <module>
    query.collectdatafor(4,2)
  File "C:\Users\myuser\PycharmProjects\WinMetrics\venv\lib\site-packages\win32\lib\win32pdhquery.py", line 448, in collectdatafor
    for ind in range(totalperiod/period):
TypeError: 'float' object cannot be interpreted as an integer

Process finished with exit code 1
```

**Comment by p71x** [comment]
It could be relic from time of conversion from Python 2 to 3 (semantic of / operator has changed), it should be converted to integer floor division:
>    for ind in range(totalperiod//period):
or to integer
>    for ind in range(int(totalperiod/period)):
