### ISSUE TITLE
"Operation aborted" when trying to send mails with outlook

### ISSUE THREAD

**Issue by grap3-fru1t** [mhammond/pywin32#1558]
The issue occurs when trying to send emails using mail.Send(). It works however, when trying to only display the mail with mail.Display()
**Code that works**:
```
import win32com.client as win32

outlook = win32.Dispatch("Outlook.Application")
mail = outlook.CreateItem(0)
mail.SentOnBehalfOfName = 'send_from.mailbox.com'
mail.To = 'to_send.mailbox@.com'
mail.Subject = 'TEST'
mail.Body = 'Test Body'
mail.BodyFormat = 1
mail.Display()
```
The mail is generated correctly. It can be sent out by manually clicking on "Send"

**Code that doesn't work**:
```
import win32com.client as win32

outlook = win32.Dispatch("Outlook.Application")
mail = outlook.CreateItem(0)
mail.SentOnBehalfOfName = 'send_from.mailbox.com'
mail.To = 'to_send.mailbox@.com'
mail.Subject = 'TEST'
mail.Body = 'Test Body'
mail.BodyFormat = 1
mail.Send()
```
**Error message**:
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    mail.Send()
  File "<COMObject CreateItem>", line 2, in Send
pywintypes.com_error: (-2147467260, 'Operation aborted', None, None)
```
It doesn't seem like an issue connecting to outlook, since the mail is being generated correctly with "Mail.Display()". However, I cannot make anything out of the displayed generic error message. Similar questions have also been raised [here](https://stackoverflow.com/questions/26807942/sending-an-email-through-python) and [here](https://stackoverflow.com/questions/60932382/send-outlook-email-using-python?noredirect=1&lq=1). The common understanding is that it relates to some outlook security settings. None solution for this has been found so far.

Version of Python:
- Python 3.8
- pywin32 227

**Comment by mhammond** [comment]
There were instructions on how to obtain support which you deleted when adding this text.

**Comment by hugostuijt** [comment]
Have you found a solution to this problem? I suddenly have this identical problem and the other sources (which you linked as well) do not solve it for me.

**Comment by M0B9-i-n** [comment]
Hi all, 

I ran into the same problem. Was anyone able to find a solution?

**Comment by JPelda** [comment]
Dear M0B9-i-n,

it is long ago, but I think it worked for me when setting the email account in ms outlook to the preferred one manually. If you then send via the same account, also specified in the python code, it should run.
Give it a try. 

Alternatively, you can save the emails to ms outlook and send them from there manually.

**Comment by pgsguedes** [comment]
Tô aqui ferrado tb, já fiz de tudo, não consigo enviar e-mail.

**Comment by pgsguedes** [comment]
Senhores, a Google mudou a maneira de enviar e-mail em 2024. Vcs têm que entrar em sua conta e gerar uma senha app. Vc cola esta senha na  password do programa Python.

**Comment by pgsguedes** [comment]
msg = EmailMessage()
    msg['Subject'] = "Assunto do email"
    msg['From']    = 'seu email@gmail.com'
    msg['To']      = 'enviar email@gmail.com'
    password = 'sua senha APP'
    msg.add_header('Content-Type', 'text/html')
    msg.set_payload(corpo_email)

**Comment by sadiqm2894** [comment]
Have anyone find a solution to this problem earlier my organisation uses wave and vdi desktops email is getting triggered but now we are migrating to cloud pc facing error in mail.send() method.
Below is the same error 
pywintypes.com_error: (-2147467260, 'Operation aborted', None, None)

Thanks in advance.
