### ISSUE TITLE
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)?

### ISSUE THREAD

**Issue by Saleem344** [mhammond/pywin32#1578]
hi,
i'm using python 3.8.5 32bit version on my windows i have downloaded pywin32 3.8 version and installed on my windows but when i run my code i'm getting the following error in output
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

my code:
       
       import win32com.client

       client = win32com.client.Dispatch('OpcLabs.EasyOpc.DataAccess.EasyDAClient')

       value = client.ReadItemValue('','OPCLabs.KitServer.2', 'Demo.Single')

       print('value:',value)

output error:
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\test.py", line 3, in <module>
    client = win32com.client.Dispatch('OpcLabs.EasyOpc.DataAccess.EasyDAClient')
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python38-32\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

can anyone help me with this??

**Comment by mhammond** [comment]
This is a support request - please see https://github.com/mhammond/pywin32#support for how to get support or to follow up. But this means that the COM object you want to use isn't installed, or if it is installed, there's a mismatch between 32bit and 64bit (it may be that both python and the com object need to be the same)
