### ISSUE TITLE
Python 3 with WSH and IID_IActiveScript

### ISSUE THREAD

**Issue by cpede** [mhammond/pywin32#1666]
I have been using the pywin32 in v2.7 together with Python 2.7:
pywin32-221.win32-py2.7.exe
python-2.7.18.msi

together with the Windows Script Hosting ActiveX interface in my C++ application.

After changing to the latest v3 the scripting engine cannot be instantiated using the IID_IActiveScript
interface, because the class is not registered?

Any idea what the problem is?

-cpede

**Comment by mhammond** [comment]
How did you install the python 3 version?

**Comment by cpede** [comment]
I first installed the python-3.9.2.exe from python.org, and then your pywin32-300.win32-py3.9.exe.
Both installer went fine, and you installer found the original Python installation.

I made a small Windows console program to show the error:

// PyWin32_v3Test.cpp : This file contains the 'main' function. Program execution begins and ends there.

#include <windows.h>
#include <activscp.h>

// {BB1A2AE1-A4F9-11cf-8F20-00805F2CD064}
DEFINE_GUID(IID_IActiveScript, 0xbb1a2ae1, 0xa4f9, 0x11cf, 0x8f, 0x20, 0x00, 0x80, 0x5f, 0x2c, 0xd0, 0x64);

int main()
{
	::CoInitializeEx(NULL, COINIT_APARTMENTTHREADED);

	CLSID clsid = GUID_NULL;
	HRESULT hr = ::CLSIDFromProgID(L"Python", &clsid);
	if (FAILED(hr)) return FALSE;

	IActiveScript* axScript = NULL;
	hr = ::CoCreateInstance(clsid, NULL, CLSCTX_ALL, IID_IActiveScript, reinterpret_cast<void**>(&axScript));
	if (FAILED(hr)) return FALSE;

	if (axScript) axScript->Release();


	// SUCCESS
	//python-2.7.18.msi from https://www.python.org/downloads/
	//pywin32-221.win32-py2.7.exe from https://deac-fra.dl.sourceforge.net/project/pywin32/pywin32/Build%20221/pywin32-221.win32-py2.7.exe


	//ERROR -> hr = REGDB_E_CLASSNOTREG "Class not registered"
	//python-3.9.2.exe from https://www.python.org/downloads/
	//pywin32-300.win32-py3.9.exe from https://github.com/mhammond/pywin32/releases
}

-cpede

**Comment by mhammond** [comment]
That looks like the 32bit version of Python 3.9 - if you executable is 64bit, then that would be expected. I believe the WSH tests all work on 3.9, so if that's not the problem I'm not surewhat it might be.

**Comment by cpede** [comment]
I’m running application in 32-bit, and Python is also 32-bit.
Does this dump help:

pythoncom error: ERROR: server.policy could not create an instance.

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\server\policy.py", line 136, in CreateInstance
    return retObj._CreateInstance_(clsid, reqIID)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\server\policy.py", line 194, in _CreateInstance_
    myob = call_func(classSpec)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\server\policy.py", line 728, in call_func
    return resolve_func(spec)(*args)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\server\policy.py", line 717, in resolve_func
    module = _import_module(mname)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\server\policy.py", line 736, in _import_module
    __import__(mname)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32comext\axscript\client\pyscript.py", line 17, in <module>
    import win32com.client.dynamic
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\client\__init__.py", line 11, in <module>
    from . import gencache
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\client\gencache.py", line 657, in <module>
    __init__()
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\client\gencache.py", line 59, in __init__
    Rebuild()
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\client\gencache.py", line 644, in Rebuild
    _SaveDicts()
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\client\gencache.py", line 66, in _SaveDicts
    f = open(os.path.join(GetGeneratePath(), "dicts.dat"), "wb")
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\client\gencache.py", line 142, in GetGeneratePath
    f = open(fname,"w")
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\Python39-32\\lib\\site-packages\\win32com\\gen_py\\__init__.py<file://Python39-32/lib/site-packages/win32com/gen_py/__init__.py>'
pythoncom error: Unexpected gateway error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\server\policy.py", line 136, in CreateInstance
    return retObj._CreateInstance_(clsid, reqIID)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\server\policy.py", line 194, in _CreateInstance_
    myob = call_func(classSpec)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\server\policy.py", line 728, in call_func
    return resolve_func(spec)(*args)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\server\policy.py", line 717, in resolve_func
    module = _import_module(mname)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\server\policy.py", line 736, in _import_module
    __import__(mname)
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32comext\axscript\client\pyscript.py", line 17, in <module>
    import win32com.client.dynamic
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\client\__init__.py", line 11, in <module>
    from . import gencache
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\client\gencache.py", line 657, in <module>
    __init__()
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\client\gencache.py", line 59, in __init__
    Rebuild()
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\client\gencache.py", line 644, in Rebuild
    _SaveDicts()
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\client\gencache.py", line 66, in _SaveDicts
    f = open(os.path.join(GetGeneratePath(), "dicts.dat"), "wb")
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\client\gencache.py", line 142, in GetGeneratePath
    f = open(fname,"w")
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\Python39-32\\lib\\site-packages\\win32com\\gen_py\\__init__.py<file://Python39-32/lib/site-packages/win32com/gen_py/__init__.py>'
pythoncom error: CPyFactory::CreateInstance failed to create instance. (80004005)

C:\Users\Dantec_PIV\source\repos\PyWin32_v3Test\Debug\PyWin32_v3Test.exe (process 10404) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .



Best regards / med venlig hilsen

Carsten Pedersen, MSc
Software Development (Point Software)

Direct +45 4457 8143

[cid:image001.png@01D70BD4.8066C4F0]

Dantec Dynamics A/S / Tonsbakken 16-18 / DK-2740 Skovlunde / Denmark
Phone +45 4457 8000 / www.dantecdynamics.com

This message (including any attachments) may contain confidential, proprietary, privileged and/or private information. The information is intended to be for the use of the individual or entity designated above. If you are not the intended recipient of this message, please notify the sender immediately, and delete the message and any attachments. Any disclosure, reproduction, distribution or other use of this message or any attachments by an individual or entity other than the intended recipient is prohibited. Please be aware of the increase in cybercrime and fraud. If you receive an email purporting to be from someone at Dantec Dynamics which seeks to direct a payment to bank details which differ from those we have already given to you via an authorized invoice signed and stamped by Dantec Dynamics, it is unlikely to be genuine. Please do not reply to the email nor act on any information contained therein but contact us immediately by phone. Please consider the environment before printing this e-mail.

**Comment by mhammond** [comment]
huh, yeah, it probably does. Can you please try removing the `C:\Program Files (x86)\Python39-32\lib\site-packages\win32com\gen_py` directory - that should cause pywin32 to use one in %TEMP%. There's a proposal somewhere I can't find to stop using `win32com\gen_py` and always just use a local writable dir which I can't find, but which I really must push forward.

**Comment by cpede** [comment]
Bingo, that makes it work :-)
Will you make a new version?

Two quick questions:
* Can I include your installation .exe in my application?
* Are there any installer switches that make the installer run unattended/silently?

**Comment by mhammond** [comment]
> Will you make a new version?

Yes, eventually, but a fix for this isn't even committed yet.

>     * Can I include your installation .exe in my application?

Sure.

>     * Are there any installer switches that make the installer run unattended/silently?

No, but the installer exe is just a .zip, so you can just manually unpack, then copy the files, then run the postinstall script manually.

**Comment by mhammond** [comment]
I wish I could find that conversation I referred to - so in the meantime we can track the non-writable gen_py directory here

**Comment by kxrob** [comment]
> 
> I wish I could find that conversation I referred to - so in the meantime we can track the non-writable gen_py directory here

https://github.com/mhammond/pywin32/issues/1143  ?

**Comment by cpede** [comment]
Now it is not working again. And I can't remember how/where I got the traceback file from? How do I read the traceback error when running my c++ program?

-cpede

**Comment by mhammond** [comment]
> How do I read the traceback error when running my c++ program?

Generally by wrapping the python code you call in try/catch and a call to `traceback.print_exc()`

**Comment by cpede** [comment]
Hmm I did not do that, since I'm not calling py code at all, only my c++ code, where the last part fails?

`CLSID clsid = GUID_NULL;
HRESULT hr = ::CLSIDFromProgID(L"Python", &clsid);
if (FAILED(hr)) return FALSE;

IActiveScript* axScript = NULL;
hr = ::CoCreateInstance(clsid, NULL, CLSCTX_ALL, IID_IActiveScript, reinterpret_cast<void**>(&axScript));
if (FAILED(hr)) return FALSE;

if (axScript) axScript->Release();`

**Comment by mhammond** [comment]
Right. Maybe registered the python com object with --debug and using win32traceutil?

**Comment by cpede** [comment]
OK I found the difference between Python 2.7 which always works and 3.9. It seems that you are copying the pythoncom27.dll and the pythoncom39.dll into the Windows /System32 folder. But 2.7 also copies the dependent python27.dll, whereas python39.dll is located in the Python installation folder. I did not setup the Environment Variables why it can't find it. Copying python39.dll into the  Windows /System32 folder makes it work (and probably also setting up the environment variable).
When installed side by side, how to I select between running the 2.7 and 3.9 versions?

**Comment by cpede** [comment]
It also looks like your pywin32 version 2.7 removed the pythoncom27.dll and Python removes the python27.dll from Windows/System32, during uninstall. But 3.8 and 3.9 forget to uninstall all files in Windows/System32 ?

**Comment by Avasam** [comment]
When debugging for https://github.com/mhammond/pywin32/issues/2492 / https://github.com/mhammond/pywin32/pull/2493, I had also noticed `site-packages/win32com/gen_py` was used (until I deleted the folder), not sure how / since when it initially created that folder.

I do have a question about the folder under `%TEMP%`, it's split up by Python minor version, but should it also be split by pywin32 version ?
![Image](https://github.com/user-attachments/assets/56e78427-f793-4554-8adb-c158094aa3d8)

And is there a reason for new pywin32 releases to re-use `gen_py` from previous versions?

**Comment by mhammond** [comment]
> When debugging for [#2492](https://github.com/mhammond/pywin32/issues/2492) / [#2493](https://github.com/mhammond/pywin32/pull/2493), I had also noticed `site-packages/win32com/gen_py` was used (until I deleted the folder), not sure how / since when it initially created that folder.

I think that was intentional to avoid breakage if that folder already existed or if people actually wanted the old behaviour. Whether that actually makes sense is a different question I guess.

> I do have a question about the folder under `%TEMP%`, it's split up by Python minor version, but should it also be split by pywin32 version ?

This is kinda tied to the above maybe - if a user has multiple Python 3.10 installations, each with a different version of pywin32, we are already into somewhat unsupported territory? Maybe that's exactly the kind of scenario where one of them does actually want gen_py inside their installation?

> And is there a reason for new pywin32 releases to re-use `gen_py` from previous versions? (not that it has caused me issues, but I also don't really use pywin32 for COM much. Just curious)

There's a case to be made that it should not, although I'm not sure we want to leave old orphaned files behind. I think the main reason it does it to avoid surprises for people to ran makepy manually - they'd find their code doesn't work in subtle ways after an upgrade (as it would move back to "dynamic dispatch" for those objects). Now that we encourage `EnsureDispatch` to run makepy it might be less of a problem.
