### ISSUE TITLE
Executing script uses pywin32 from C++.

### ISSUE THREAD

**Issue by j3su5cr1st** [mhammond/pywin32#1693]
I'm using python39 with static linkage in my C++ app and call python script uses win32pipe and win32file. Every run I enforce an error ``` ImportError: DLL load failed while importing win32file: The specified module could not be found. ```. All paths to modules are configured via ``` PyConfig ``` so it looks like
```c++
        wchar_t* filename = Py_DecodeLocale(argv[0], nullptr);
        auto pySysPath = _getPySysPath();

        std::wstring pathVar = pySysPath;
        const wchar_t* path = _wgetenv(L"PATH");
        if (path) {
            pathVar += path;
        }

        Py_SetPath(pathVar.c_str());
        Py_SetPythonHome(_wgetenv(L"PYROOT"));
        Py_SetProgramName(filename);

        PyConfig pyConfig;
        PyConfig_InitIsolatedConfig(&pyConfig);
        PyConfig_SetBytesArgv(&pyConfig, argc, argc ? argv : nullptr);
        PyConfig_SetString(&pyConfig, &pyConfig.pythonpath_env, pySysPath.c_str());
        PyConfig_SetString(&pyConfig, &pyConfig.program_name, pyProgramName);
        Py_DebugFlag = true;
        pyConfig.isolated = false;
        pyConfig.dev_mode = true;
        pyConfig.verbose = 2;
        pyConfig.parse_argv = true;
        pyConfig.dev_mode = true;
        pyConfig.use_environment = true;
        pyConfig.write_bytecode = true;

        auto status = Py_InitializeFromConfig(&pyConfig);
        if (PyStatus_Exception(status)) {
            Py_ExitStatusException(status);
        }
``` 

and paths I generated from _getPySysPath() uses this:
```c++
    static const std::vector<const wchar_t*> _pySysPathes = {
            L"Lib\\site-packages\\pywin32_system32",
            L"Lib\\site-packages\\win32",
            L"Lib\\site-packages",
            L"python39.zip",
            L"DLLs",
            L"lib",
            L"lib\\site-packages",
            L"lib\\site-packages\\win32",
            L"lib\\site-packages\\win32\\lib",
            L"lib\\site-packages\\Pythonwin"};
```
Despite my error, there's no error while I use python3.9 which has been installed on my system as binary from the official site.

P.S.
Verbose level 2 tells me that an error occurs in ``` _find_and_load ``` but it's telling me nothing.
Full backtrace:
```
# code object from 'C:\\Users\\j35u5\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\win32\\lib\\__pycache__\\pywin32_bootstrap.cpython-39.pyc'
import 'pywin32_bootstrap' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D305D83BB0>
# trying C:\Users\j35u5\AppData\Local\Programs\Python\Python39\Lib\site-packages\pywin32_system32\win32file.cp39-win_amd64.pyd
# trying C:\Users\j35u5\AppData\Local\Programs\Python\Python39\Lib\site-packages\pywin32_system32\win32file.pyd
# trying C:\Users\j35u5\AppData\Local\Programs\Python\Python39\Lib\site-packages\pywin32_system32\win32file.py
# trying C:\Users\j35u5\AppData\Local\Programs\Python\Python39\Lib\site-packages\pywin32_system32\win32file.pyw
# trying C:\Users\j35u5\AppData\Local\Programs\Python\Python39\Lib\site-packages\pywin32_system32\win32file.pyc
# trying C:\Users\j35u5\AppData\Local\Programs\Python\Python39\Lib\site-packages\win32\win32file.cp39-win_amd64.pyd
# trying C:\Users\j35u5\AppData\Local\Programs\Python\Python39\Lib\site-packages\win32\win32file.pyd
# trying C:\Users\j35u5\AppData\Local\Programs\Python\Python39\lib\encodings\ascii.cp39-win_amd64.pyd
# trying C:\Users\j35u5\AppData\Local\Programs\Python\Python39\lib\encodings\ascii.pyd
# trying C:\Users\j35u5\AppData\Local\Programs\Python\Python39\lib\encodings\ascii.py
# C:\Users\j35u5\AppData\Local\Programs\Python\Python39\lib\encodings\__pycache__\ascii.cpython-39.pyc matches C:\Users\j35u5\AppData\Local\Programs\Python\Python39\lib\encodings\ascii.py
# code object from 'C:\\Users\\j35u5\\AppData\\Local\\Programs\\Python\\Python39\\lib\\encodings\\__pycache__\\ascii.cpython-39.pyc'
import 'encodings.ascii' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D305D833A0>
Traceback (most recent call last):
  File "C:\Users\j35u5\Sources\scanner\src\pymodules\test.py", line 2, in <module>
    import win32file
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1108, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: DLL load failed while importing win32file: The specified module could not be found.
```

**Comment by j3su5cr1st** [comment]
More information I got 
![image](https://user-images.githubusercontent.com/45117783/115994325-37f49d00-a5df-11eb-9c58-752c4210be48.png)

**Comment by j3su5cr1st** [comment]
And x86 application
![image](https://user-images.githubusercontent.com/45117783/115994490-d254e080-a5df-11eb-84bf-c7e833dabefe.png)

**Comment by j3su5cr1st** [comment]
Solved. The problem was in pywin32 dependencies. It requires python.dll in release build in DLL (pyd) manifest and python_d.dll in debug build for some modules (such as win32file), therefore it doesn't matter your binary is python, you also should link it dynamically.

I think that @mhammond can pull debug builds for pywin32 to make it possible to debug embedded python and make it possible to build libraries without DLL dependencies for embedded usage.

**Comment by mhammond** [comment]
I don't understand this:

> Solved. The problem was in pywin32 dependencies. It requires python.dll in release build in DLL (pyd) manifest and python_d.dll in debug build for some modules (such as win32file), therefore it doesn't matter your binary is python, you also should link it dynamically.

Python itself uses _d for debug builds, not just pywin32. I'm also not sure what you are suggesting should be done dynamically - certainly extension modules loading Python dynamically isn't an option.


> I think that @mhammond can pull debug builds for pywin32 to make it possible to debug embedded python and make it possible to build libraries without DLL dependencies for embedded usage.

I'm not sure what this means either. Pull them from where? Or maybe you mean make them available? If so, I suggest you just build them yourself.

Either way, I'm glad it's working for you and nothing here seems actionable by me.
