### ISSUE TITLE
ImportError: DLL load failed while importing win32gui: The specified method not found.

### ISSUE THREAD

**Issue by SakhnevichKirill** [mhammond/pywin32#1736]
I am trying to package it .py together with win32gui and due to my inexperience I do not understand how to fix this error. If this is possible, help me please find what is missing in the spec file and what needs to be done to solve this problem?

I am using windows 10 x64, python 3.8 and pywin32==300

Test.py
``` Test.py
import win32.win32gui as win32gui
def winEnumHandler( hwnd, ctx ):
    if win32gui.IsWindowVisible(hwnd):
        print(hex(hwnd), win32gui.GetWindowText(hwnd))

win32gui.EnumWindows(winEnumHandler, None)
```
Test.spec
``` Test.spec
# -*- mode: python ; coding: utf-8 -*-
options = [ ('v', None, 'OPTION'), ('W ignore', None, 'OPTION') ]

block_cipher = None

a = Analysis(['Test.py'],
             pathex=['D:\\Games\\InterceptionBot\\bot-master3'],
             binaries=[("virt3\\Lib\\site-packages\\pywin32_system32\\", "pywin32_system32\\")],
             datas=[],
             hiddenimports=[
             "virt3\\Lib\\site-packages\\pywin32_system32",
             "virt3\\Lib\\site-packages\\pythonwin",
             "virt3\\Lib\\site-packages\\win32",
             "virt3\\Lib\\site-packages\\win32com",
             "virt3\\Lib\\site-packages\\win32comext",
             "virt3\\Lib\\site-packages\\win32ctypes"
             ],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          options,
          [],
          name='Test',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )
```

``` cmd
> **pyinstaller --onefile Test.spec**
5698 INFO: Building EXE from EXE-00.toc completed successfully.
```

``` cmd
>dist\Test.exe
import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'nt' # <class '_frozen_importlib.BuiltinImporter'>
import _thread # previously loaded ('_thread')
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import _weakref # previously loaded ('_weakref')
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import 'winreg' # <class '_frozen_importlib.BuiltinImporter'>
# installing zipimport hook
import 'time' # <class '_frozen_importlib.BuiltinImporter'>
import 'zipimport' # <class '_frozen_importlib.FrozenImporter'>
# installed zipimport hook
# zipimport: found 148 names in 'C:\\Users\\user\\AppData\\Local\\Temp\\_MEI194282\\base_library.zip'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import codecs # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\codecs.pyc
import encodings.aliases # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\encodings\aliases.pyc
import encodings # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\encodings\__init__.pyc
import encodings.utf_8 # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\encodings\utf_8.pyc
import encodings.cp1251 # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\encodings\cp1251.pyc
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
import encodings.latin_1 # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\encodings\latin_1.pyc
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import abc # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\abc.pyc
import io # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\io.pyc
import warnings # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\warnings.pyc
import '_struct' # <class '_frozen_importlib.BuiltinImporter'>
import 'zlib' # <class '_frozen_importlib.BuiltinImporter'>
# PyInstaller: FrozenImporter(D:\Games\InterceptionBot\bot-master3\dist\Test.exe?6178397)
import os # PyInstaller PYZ
import stat # PyInstaller PYZ
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
# _collections_abc not found in PYZ
import _collections_abc # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\_collections_abc.pyc
import ntpath # PyInstaller PYZ
import genericpath # PyInstaller PYZ
import 'genericpath' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import 'ntpath' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import 'os' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import ctypes # PyInstaller PYZ
# _ctypes not found in PYZ
# extension module '_ctypes' loaded from 'C:\\Users\\user\\AppData\\Local\\Temp\\_MEI194282\\_ctypes.pyd'
# extension module '_ctypes' executed from 'C:\\Users\\user\\AppData\\Local\\Temp\\_MEI194282\\_ctypes.pyd'
import '_ctypes' # <_frozen_importlib_external.ExtensionFileLoader object at 0x0000019B3C1F02E0>
import ctypes._endian # PyInstaller PYZ
import 'ctypes._endian' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import 'ctypes' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import pkgutil # PyInstaller PYZ
# collections not found in PYZ
# operator not found in PYZ
import '_operator' # <class '_frozen_importlib.BuiltinImporter'>
import operator # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\operator.pyc
# keyword not found in PYZ
import keyword # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\keyword.pyc
# heapq not found in PYZ
import '_heapq' # <class '_frozen_importlib.BuiltinImporter'>
import heapq # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\heapq.pyc
import 'itertools' # <class '_frozen_importlib.BuiltinImporter'>
# reprlib not found in PYZ
import reprlib # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\reprlib.pyc
import '_collections' # <class '_frozen_importlib.BuiltinImporter'>
import collections # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\collections\__init__.pyc
# functools not found in PYZ
import '_functools' # <class '_frozen_importlib.BuiltinImporter'>
import functools # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\functools.pyc
import importlib # PyInstaller PYZ
# types not found in PYZ
import types # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\types.pyc
import 'importlib' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import importlib.util # PyInstaller PYZ
import importlib.abc # PyInstaller PYZ
import importlib.machinery # PyInstaller PYZ
import 'importlib.machinery' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import 'importlib.abc' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import contextlib # PyInstaller PYZ
import 'contextlib' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import 'importlib.util' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
# weakref not found in PYZ
# _weakrefset not found in PYZ
import _weakrefset # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\_weakrefset.pyc
import weakref # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\weakref.pyc
import 'pkgutil' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
# re not found in PYZ
# enum not found in PYZ
import enum # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\enum.pyc
# sre_compile not found in PYZ
import '_sre' # <class '_frozen_importlib.BuiltinImporter'>
# sre_parse not found in PYZ
# sre_constants not found in PYZ
import sre_constants # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\sre_constants.pyc
import sre_parse # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\sre_parse.pyc
import sre_compile # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\sre_compile.pyc
import '_locale' # <class '_frozen_importlib.BuiltinImporter'>
# copyreg not found in PYZ
import copyreg # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\copyreg.pyc
import re # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\re.pyc
import multiprocessing # PyInstaller PYZ
import multiprocessing.context # PyInstaller PYZ
import threading # PyInstaller PYZ
import 'threading' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import multiprocessing.process # PyInstaller PYZ
import signal # PyInstaller PYZ
import 'signal' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import 'multiprocessing.process' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import multiprocessing.reduction # PyInstaller PYZ
import pickle # PyInstaller PYZ
import _compat_pickle # PyInstaller PYZ
import '_compat_pickle' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import '_pickle' # <class '_frozen_importlib.BuiltinImporter'>
# org not found in PYZ
import 'pickle' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import socket # PyInstaller PYZ
# _socket not found in PYZ
# extension module '_socket' loaded from 'C:\\Users\\user\\AppData\\Local\\Temp\\_MEI194282\\_socket.pyd'
# extension module '_socket' executed from 'C:\\Users\\user\\AppData\\Local\\Temp\\_MEI194282\\_socket.pyd'
import '_socket' # <_frozen_importlib_external.ExtensionFileLoader object at 0x0000019B3DBE3FA0>
import selectors # PyInstaller PYZ
# collections.abc not found in PYZ
import collections.abc # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\collections\abc.pyc
import 'math' # <class '_frozen_importlib.BuiltinImporter'>
# select not found in PYZ
# extension module 'select' loaded from 'C:\\Users\\user\\AppData\\Local\\Temp\\_MEI194282\\select.pyd'
# extension module 'select' executed from 'C:\\Users\\user\\AppData\\Local\\Temp\\_MEI194282\\select.pyd'
import 'select' # <_frozen_importlib_external.ExtensionFileLoader object at 0x0000019B3DC0B6A0>
import 'selectors' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import 'errno' # <class '_frozen_importlib.BuiltinImporter'>
import 'socket' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import '_winapi' # <class '_frozen_importlib.BuiltinImporter'>
import 'multiprocessing.reduction' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import 'multiprocessing.context' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import 'multiprocessing' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import multiprocessing.spawn # PyInstaller PYZ
import runpy # PyInstaller PYZ
import 'runpy' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import multiprocessing.util # PyInstaller PYZ
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
import subprocess # PyInstaller PYZ
import 'msvcrt' # <class '_frozen_importlib.BuiltinImporter'>
import 'subprocess' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import 'multiprocessing.util' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import 'multiprocessing.spawn' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import multiprocessing.popen_spawn_win32 # PyInstaller PYZ
import 'multiprocessing.popen_spawn_win32' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import inspect # PyInstaller PYZ
import dis # PyInstaller PYZ
import opcode # PyInstaller PYZ
import '_opcode' # <class '_frozen_importlib.BuiltinImporter'>
import 'opcode' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import 'dis' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
# linecache not found in PYZ
import tokenize # PyInstaller PYZ
import token # PyInstaller PYZ
import 'token' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import 'tokenize' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import linecache # loaded from Zip C:\Users\user\AppData\Local\Temp\_MEI194282\base_library.zip\linecache.pyc
import 'inspect' # <pyimod03_importers.FrozenImporter object at 0x0000019B3C06DEE0>
import win32 # PyInstaller PYZ
import 'win32' # <_frozen_importlib_external._NamespaceLoader object at 0x0000019B3DEB65B0>
# win32.win32gui not found in PYZ
Traceback (most recent call last):
  File "Test.py", line 1, in <module>
    import win32.win32gui as win32gui
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing win32gui: The specified module not found.
[22176] Failed to execute script 'Test' due to unhandled exception!

```

**Comment by mhammond** [comment]
The problem is almost certainly a duplicate pywintypesXX.dll, and the wrong one is being found - win32gui and pywintypesXX.dll must have the same version number (which you can view using Windows Explorer "details" for the file).
