### ISSUE TITLE
Problem to move an outlook mail that contains chinese characters into a subfolder

### ISSUE THREAD

**Issue by Ludo915** [mhammond/pywin32#1743]
Hi,

I am trying to move an outlook email into an outlook subfolder, this works in my script for many mails except in this case for a mail that contains chinese characters... Any ideas?

* Expected behavior and actual behavior.
Move an outlook mail into a subfolder
Error message: 
`'The items were copied instead of moved because the original items cannot be deleted. The item cannot be deleted. It was either moved or already deleted, or access was denied.', None, 0, -2147219840), None)`
* Steps to reproduce the problem.
`x.Move(self.folder.Folders("Inbox").Folders("VALORISATIONS").Folders("KGI"))`
* Version of Python and pywin32
recent
![chinesecharacters](https://user-images.githubusercontent.com/18355451/129106649-83332b47-012f-4ce4-8b93-7b43161cfa63.PNG)

**Comment by Ludo915** [comment]
These are the chinese caracters in the signature: 何立凱  Seb Ho, CFA
債券投資管理部 經理

**Comment by Ludo915** [comment]
The error appears again in another case, is it possible that it could be due to the fact that a copy of the mail I am trying to move already is in the folder of destination? Is there a way to decide to crush the pre-existing email in the folder?:

```
 21%|██        | 448/2154 [05:53<22:25,  1.27it/s]
Traceback (most recent call last):
  File "C:/Users/giraudl/PycharmProjects/AutomatePDP/AutomatePDP.py", line 1114, in <module>
    GestionBoitePDP.get_mail_print_to_csv(skipgetpasswords = "Y")
  File "C:/Users/giraudl/PycharmProjects/AutomatePDP/AutomatePDP.py", line 1104, in get_mail_print_to_csv
    self.case_select(macro_to_call,x,attachments)
  File "C:/Users/giraudl/PycharmProjects/AutomatePDP/AutomatePDP.py", line 77, in case_select
    switcher = {
  File "C:/Users/giraudl/PycharmProjects/AutomatePDP/AutomatePDP.py", line 183, in ALLIANZ
    x.Move(self.folder.Folders("Inbox").Folders("VALORISATIONS").Folders("ALLIANZ"))
  File "<COMObject <unknown>>", line 2, in Move
pywintypes.com_error: (-2147352567, 'Exception occurred.', (4096, 'Microsoft Outlook', "Les éléments ont été copiés et non pas déplacés, car les éléments d'origine ne peuvent pas être supprimés. Impossible de supprimer cet élément. Il a été déplacé ou supprimé, ou l'accès a été refusé.", None, 0, -2147219840), None)
```
