### ISSUE TITLE
Pywin32-302 breaks site.py

### ISSUE THREAD

**Issue by nnpok** [mhammond/pywin32#1770]
Pywin32-302 breaks site.py when importing other modules in a virtual environment. Downgrading to 301 is a workaround for now.

This seems related to a previous issue in release 226: [Pywin32 - Release 226 breaks Virtualenv. #1439](https://github.com/mhammond/pywin32/issues/1439)

**Expected behavior and actual behavior.** 
- Pip installation of packages in virtual environments after having installed `pywin32` should work.

**Steps to reproduce the problem.**
I'm not exactly sure what is happening but it seems like `pywin32-302` overrides the site.py module to a degree:
```
Failed to import the site module
Traceback (most recent call last):
  File "C:\venv\lib\site.py", line 703, in <module>
    main()
  File "C:\venv\lib\site.py", line 683, in main
    paths_in_sys = addsitepackages(paths_in_sys)
  File "C:\venv\lib\site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "C:\venv\lib\site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "C:\venv\lib\site.py", line 173, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pywin32_bootstrap'
```

**Version of Python and pywin32**
Python 3.6.8, pywin32-302

**Comment by Avasam** [comment]
There's been many improvements to module loading since then.
@nnpok Is this still a problem for you?  (Python 3.9+, pywin32 312+) This issue is missing an actual reproducer.
