### ISSUE TITLE
unable to import win32.client

### ISSUE THREAD

**Issue by Charles-God** [mhammond/pywin32#1807]
version of Python: 3.10
version of pywin32:302
when I
`import win32com.client`
it returns
`Traceback (most recent call last):
  File "D:\Python\try.py", line 52, in <module>
    import win32com.client
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\win32com\__init__.py", line 5, in <module>
    import win32api, sys, os
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\win32api\__init__.py", line 1, in <module>
    from win32.api import *
ModuleNotFoundError: No module named 'win32.api'`

How can I import win32.api?

**Comment by mhammond** [comment]
there is no module called `win32.api` - there is one `win32api`. For more help, see https://github.com/mhammond/pywin32/blob/master/README.md#support
