### ISSUE TITLE
Pywin32 ImportError: DLL load failed while importing win32gui

### ISSUE THREAD

**Issue by JKKSI** [mhammond/pywin32#1837]
Hello there, this is what happends, i have the next problem....
i made a script that uses library win32gui and win32console from pywin32 , when i run my python script in .py, executes normally
, when i execute my python file but in .exe show me the next error...
```
Traceback (most recent call last):
  File "<dist\obf\lala.py>", line 4, in <module>
  File "<frozen lala.py>", line 23, in <module>
ImportError: DLL load failed while importing win32gui: No se puede encontrar el módulo especificado.
[9780] Failed to execute script 'lala.py' due to unhandled exception!
```
my python version is 
```
C:\Users\Daishinkan\AppData\Roaming\Python\Python310>python --version
Python 3.10.2
```
my pywin is Version: 303
I have tried Reinstallin with pip uninstall pywin32, later tried reinstalling again with pip install pywin32
i have the same error later of reinstalling the package, so then i have tried the next...
```
C:\Windows\system32>pip install pywin32==300
ERROR: Could not find a version that satisfies the requirement pywin32==300 (from versions: 302, 303)
ERROR: No matching distribution found for pywin32==300
```
I have tried with version 226, and 228 and is same result, so then finally i have tried the next...
```
C:\Users\Daishinkan\AppData\Roaming\Python\Python310>python Scripts/pywin32_postinstall.py -install
Parsed arguments are: Namespace(install=True, remove=False, wait=None, silent=False, quiet=False, destination='C:\\Program Files\\Python310\\Lib\\site-packages')
Traceback (most recent call last):
  File "C:\Users\Daishinkan\AppData\Roaming\Python\Python310\Scripts\pywin32_postinstall.py", line 763, in <module>
    install(args.destination)
  File "C:\Users\Daishinkan\AppData\Roaming\Python\Python310\Scripts\pywin32_postinstall.py", line 429, in install
    LoadSystemModule(lib_dir, "pywintypes")
  File "C:\Users\Daishinkan\AppData\Roaming\Python\Python310\Scripts\pywin32_postinstall.py", line 192, in LoadSystemModule
    mod = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing pywintypes: No se puede encontrar el módulo especificado.

```
I dont know what to do for fix, i guess is a bug, this is the first time that happends to me, i hope a answer soon, thanks for reading :)

**Comment by mhammond** [comment]
Please see if https://github.com/mhammond/pywin32#the-specified-procedure-could-not-be-found--entry-point-not-found-errors helps
