### ISSUE TITLE
Invalid class string error when trying connect to PowerPoint or Word

### ISSUE THREAD

**Issue by mnpica** [mhammond/pywin32#1914]
* Expected behavior and actual behavior.
I am trying to connect to PowerPoint or Word with Python but the following line throws the com_error

`import win32com.client`
`try:`
`      xl = win32com.client.Dispatch('PowerPoint.Application')`
`except:`
         `     xl = win32com.client.DispatchEx('PowerPoint.Application')`
`finally:`
    `xl = win32com.client.gencache.EnsureDispatch('PowerPoint.Application')`

Traceback (most recent call last):
  File "D:\Python\InspectorUSB\venv\lib\site-packages\win32com\client\dynamic.py", line 86, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Python/InspectorUSB/test/test2.py", line 45, in <module>
    xl = win32com.client.Dispatch('PowerPoint.Application')
  File "D:\Python\InspectorUSB\venv\lib\site-packages\win32com\client\__init__.py", line 117, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch, userName, clsctx)
  File "D:\Python\InspectorUSB\venv\lib\site-packages\win32com\client\dynamic.py", line 106, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "D:\Python\InspectorUSB\venv\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch, None, clsctx, pythoncom.IID_IDispatch
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Python/InspectorUSB/test/test2.py", line 47, in <module>
    xl = win32com.client.DispatchEx('PowerPoint.Application')
  File "D:\Python\InspectorUSB\venv\lib\site-packages\win32com\client\__init__.py", line 146, in DispatchEx
    clsid, None, clsctx, serverInfo, (pythoncom.IID_IDispatch,)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\InspectorUSB\venv\lib\site-packages\win32com\client\dynamic.py", line 86, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Python/InspectorUSB/test/test2.py", line 49, in <module>
    xl = win32com.client.gencache.EnsureDispatch('PowerPoint.Application')
  File "D:\Python\InspectorUSB\venv\lib\site-packages\win32com\client\gencache.py", line 618, in EnsureDispatch
    disp = win32com.client.Dispatch(prog_id)
  File "D:\Python\InspectorUSB\venv\lib\site-packages\win32com\client\__init__.py", line 117, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch, userName, clsctx)
  File "D:\Python\InspectorUSB\venv\lib\site-packages\win32com\client\dynamic.py", line 106, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "D:\Python\InspectorUSB\venv\lib\site-packages\win32com\client\dynamic.py", line 89, in _GetGoodDispatch
    IDispatch, None, clsctx, pythoncom.IID_IDispatch
pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)

Process finished with exit code 1

* Steps to reproduce the problem.

I've tried  'PowerPoint.Application'  and 'Word.Application' ,then got the same error.
But 'Excel.Application' and 'Outlook.Application' worked fine.  

* Version of Python and pywin32
python 3.6.8  ,pywin32 302,Windows 11 21H2 22000.795, Microsoft 365
python 3.6.8  ,pywin32 304,Windows 11 21H2 22000.795, Microsoft 365

**Comment by mhammond** [comment]
Sorry for the delay, but `pywintypes.com_error: (-2147221005, 'Invalid class string', None, None)` is COM saying that the app isn't installed or correctly registered, so there's nothing we can do here.

**Comment by Ravir6148** [comment]
but in most of case app is installed and working fine.
