### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none) ERROR: No matching distribution found for pywin32  

### ISSUE THREAD

**Issue by QGB** [mhammond/pywin32#1920]
```
Python 3.9.11 (main, Mar 18 2022, 16:54:01)  [GCC 11.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

Parsed arguments are: Namespace(install=True, remove=False, wait=None, silent=False, quiet=False, destination='C:\\Program Files\\GIMP 2.99\\lib\\python3.9\\site-packages')
Traceback (most recent call last):
  File "C:\QGB\miniforge3\Scripts\pywin32_postinstall.py", line 763, in <module>
    install(args.destination)
  File "C:\QGB\miniforge3\Scripts\pywin32_postinstall.py", line 429, in install
    LoadSystemModule(lib_dir, "pywintypes")
  File "C:\QGB\miniforge3\Scripts\pywin32_postinstall.py", line 192, in LoadSystemModule
    mod = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: DLL load failed while importing pywintypes: 找不到指定的模块。

```
==
```
pip install pywin32 
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32
```

**Comment by mhammond** [comment]
see https://github.com/mhammond/pywin32/blob/main/README.md#support and https://github.com/mhammond/pywin32/blob/main/README.md#the-specified-procedure-could-not-be-found--entry-point-not-found-errors

**Comment by QGB** [comment]
i am using mingw_x64 python

**Comment by mhammond** [comment]
There are no binaries released for mingw, you need to build it from source (which *should* work, or be close to working, but see also #1552)
