### ISSUE TITLE
no module named win32api

### ISSUE THREAD

**Issue by DmitryDresovichDronov** [mhammond/pywin32#1929]
Install pywin32
Run under ironpython
and it dosnt work
Traceback (most recent call last):
  File "<string>", line 51, in <module>
  File "C:\Python38\Lib\site-packages\win32com\__init__.py", line 5, in <module>
ImportError: No module named win32api

can we run it under ironpython?

**Comment by DmitryDresovichDronov** [comment]
Ok thx. Whell ) Need to find some another way. )
Have a good working day! 
https://youtu.be/TFjmvfRvjTc
