### ISSUE TITLE
Wintypes error and invalid classstring

### ISSUE THREAD

**Issue by Henkie69** [mhammond/pywin32#2007]
Hi, got some headache from the error codes. Tried everything including path check, different versions en interpreters 32-64 bit but nothing works. 

Is it possible to add classes manually?

Traceback (most recent call last):
  File "C:\Users\dfdis\AppData\Local\Programs\Python\Python39\lib\site-packages\win32com\client\dynamic.py", line 86, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221005, 'Ongeldige klassereeks', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dfdis\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1885, in __call__
    return self.func(*args)
  File "C:\Users\dfdis\Documents\PaPri v4.0\main.py", line 601, in <lambda>
    command=lambda: [self.getPageNumbersToPrint('DYMO')]) # [self.getPageNumbersToPrint(pagesInPdf)])
  File "C:\Users\dfdis\Documents\PaPri v4.0\main.py", line 654, in getPageNumbersToPrint
    pdf_to_dymo_labels.printMultipleLabels(prepared_list_for_label)
  File "C:\Users\dfdis\Documents\PaPri v4.0\pdf_to_dymo_labels.py", line 215, in printMultipleLabels
    labelCom = Dispatch('Dymo.DymoAddIn')
  File "C:\Users\dfdis\AppData\Local\Programs\Python\Python39\lib\site-packages\win32com\client\__init__.py", line 117, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch, userName, clsctx)
  File "C:\Users\dfdis\AppData\Local\Programs\Python\Python39\lib\site-packages\win32com\client\dynamic.py", line 106, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Users\dfdis\AppData\Local\Programs\Python\Python39\lib\site-packages\win32com\client\dynamic.py", line 88, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(
pywintypes.com_error: (-2147221005, 'Ongeldige klassereeks', None, None)

**Comment by mhammond** [comment]
This is not a bug in pywin32, but an error from COM telling you that the COM object you are trying to use is not installed. See https://github.com/mhammond/pywin32/blob/master/README.md#support for more.
