### ISSUE TITLE
collision between PySide6 & pyttsx3 & cherrypy

### ISSUE THREAD

**Issue by orangefabri** [mhammond/pywin32#2017]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.
Expected behavior : PySide6 runs well with pyttsx3 and cherrypy.
Actual behavior :  Using only PySide6 or only pyttsx3 or only CherryPy works great. I even connected to UAV and flies with PySide6 alone. but when I combine PySide6 & pyttsx3 & cherrypy code together, something related to pywin32 collide. I don't know why, but when I uninstall pywin32 the PySide6 & cherrypy works well, it is weird thing.
the error message seems to be an pywin32 bug.

* Steps to reproduce the problem.
Here is an example code that reproduces the problem:
```
import sys
import pyttsx3
from PySide6.QtWidgets import QApplication, QMainWindow, QPushButton

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()

        self.button = QPushButton("Play")
        self.button.clicked.connect(self.play_sound)
        self.setCentralWidget(self.button)

        self.engine = pyttsx3.init()

    def play_sound(self):
        self.engine.say("hello")
        self.engine.runAndWait()

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
```

This is the error message I received in pycharm run console :

```
C:\Users\hlfan.conda\envs\UAV_GCS\python.exe C:/Users/hlfan/PycharmProjects/speak_practice/main.py
Traceback (most recent call last):
File "C:\Users\hlfan.conda\envs\UAV_GCS\lib\site-packages\pyttsx3_init_.py", line 20, in init
eng = _activeEngines[driverName]
File "C:\Users\hlfan.conda\envs\UAV_GCS\lib\[weakref.py](http://weakref.py/)", line 137, in getitem
o = self.data[key](https://forum.qt.io/topic/142951/there-seems-to-be-an-incompatibility-between-pyside6-and-pyttsx3)
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\hlfan.conda\envs\UAV_GCS\lib\[tokenize.py](http://tokenize.py/)", line 330, in find_cookie
line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\hlfan\PycharmProjects\speak_practice\[main.py](http://main.py/)", line 21, in <module>
window = MainWindow()
File "C:\Users\hlfan\PycharmProjects\speak_practice\[main.py](http://main.py/)", line 13, in init
self.engine = pyttsx3.init()
File "C:\Users\hlfan.conda\envs\UAV_GCS\lib\site-packages\pyttsx3_init_.py", line 22, in init
eng = Engine(driverName, debug)
File "C:\Users\hlfan.conda\envs\UAV_GCS\lib\site-packages\pyttsx3\[engine.py](http://engine.py/)", line 30, in init
self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
File "C:\Users\hlfan.conda\envs\UAV_GCS\lib\site-packages\pyttsx3\[driver.py](http://driver.py/)", line 50, in init
self.module = importlib.import_module(name)
File "C:\Users\hlfan.conda\envs\UAV_GCS\lib\importlib_init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "C:\Users\hlfan.conda\envs\UAV_GCS\lib\site-packages\pyttsx3\drivers\[sapi5.py](http://sapi5.py/)", line 10, in <module>
import pythoncom
File "C:\Users\hlfan.conda\envs\UAV_GCS\lib\site-packages\[pythoncom.py](http://pythoncom.py/)", line 2, in <module>
import pywintypes
File "shibokensupport/signature/loader.py", line 61, in feature_imported
File "shibokensupport/feature.py", line 137, in feature_imported
File "shibokensupport/feature.py", line 148, in _mod_uses_pyside
File "C:\Users\hlfan.conda\envs\UAV_GCS\lib\[inspect.py](http://inspect.py/)", line 1024, in getsource
lines, lnum = getsourcelines(object)
File "C:\Users\hlfan.conda\envs\UAV_GCS\lib\[inspect.py](http://inspect.py/)", line 1006, in getsourcelines
lines, lnum = findsource(object)
File "C:\Users\hlfan.conda\envs\UAV_GCS\lib\[inspect.py](http://inspect.py/)", line 831, in findsource
lines = linecache.getlines(file, module.dict)
File "C:\Users\hlfan.conda\envs\UAV_GCS\lib\[linecache.py](http://linecache.py/)", line 46, in getlines
return updatecache(filename, module_globals)
File "C:\Users\hlfan.conda\envs\UAV_GCS\lib\[linecache.py](http://linecache.py/)", line 136, in updatecache
with tokenize.open(fullname) as fp:
File "C:\Users\hlfan.conda\envs\UAV_GCS\lib\[tokenize.py](http://tokenize.py/)", line 394, in open
encoding, lines = detect_encoding(buffer.readline)
File "C:\Users\hlfan.conda\envs\UAV_GCS\lib\[tokenize.py](http://tokenize.py/)", line 371, in detect_encoding
encoding = find_cookie(first)
File "C:\Users\hlfan.conda\envs\UAV_GCS\lib\[tokenize.py](http://tokenize.py/)", line 335, in find_cookie
raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for 'C:\Users\hlfan\.conda\envs\UAV_GCS\lib\site-packages\pywin32_system32\pywintypes39.dll'

Process finished with exit code 1
```

* Version of Python and pywin32
Python : 3.6.19(latest), using anaconda and pycharm, virtual env
pywin32 : 305(latest)
pypiwin32 : 223

**Comment by orangefabri** [comment]
installing pywin32==227 and solves problem between PySide6 & CheeryPy, but pyttsx3 always generate error message related to pywin32.

**Comment by mhammond** [comment]
You must not use pypiwin32 with pywin32. But more generally, you aren't importing any pywin32 modules here - shouldn't you be reporting this bug to whoever is using pywin32?

**Comment by orangefabri** [comment]
1. Yes. I don't import pywin32 module in my main code. so it was fault of libraries using pywin32. sorry. after I install older versions of my modules with many tries, problem solved.
I thought it was some encoding problem of pywin32

2. using pypiwin32 and pywin32 seems to be okay until now. my program is still working with two libraries well. pyttsx3 needs pypiwin32 and other module need pywin32.
