### ISSUE TITLE
Standalone installer doesn't register COM-Server / postwin32_postinstall.py fails either

### ISSUE THREAD

**Issue by andreygursky** [mhammond/pywin32#2037]
* Expected behavior and actual behavior.

  * expected: pywin32 COM-Server can be used from a C++ COM-client program out-of-the-box.
  * actual: it doesn't work.

* Steps to reproduce the problem.

  * Remove previously installed pywin32 305 and Python 3.11.1 amd64 (for all users) on Win10.
  * Install Python 3.11.2 amd64 (for all users, thus default path is ```C:\Program Files\Python311```).
  * Install pywin32 306 for Python 3.11 amd64 using (deprecated) installer.
  * Run some simple C++ COM-client program using ```CLSIDFromProgID(L"Python", &clsid)``` and ```CoCreateInstance(clsid, ...)```. ```CLSIDFromProgID()``` fails.
  * Open ```cmd.exe``` as Administrator. Manually calling ```pywin32_postinstall.py``` script fails either:
```
c:\Program Files\Python311>python --version
Python 3.11.2

c:\Program Files\Python311>python Scripts\pywin32_postinstall.py -install
Parsed arguments are: Namespace(install=True, remove=False, wait=None, silent=False, quiet=False, destination='c:\\Program Files\\Python311\\Lib\\site-packages')
Traceback (most recent call last):
  File "c:\Program Files\Python311\Scripts\pywin32_postinstall.py", line 783, in <module>
    main()
  File "c:\Program Files\Python311\Scripts\pywin32_postinstall.py", line 775, in main
    install(args.destination)
  File "c:\Program Files\Python311\Scripts\pywin32_postinstall.py", line 432, in install
    LoadSystemModule(lib_dir, "pywintypes")
  File "c:\Program Files\Python311\Scripts\pywin32_postinstall.py", line 194, in LoadSystemModule
    mod = importlib.util.module_from_spec(spec)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1233, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing pywintypes: The specified module could not be found.
```

* Version of Python and pywin32
  * Python 3.11.2 amd64
  * pywin32 306

This is a regression compared to pywin32 305 and older, which are working (with the only needed manual workaround after install: remove ```gen_py``` in ```Lib\site-packages\win32com\```).

**Comment by Avasam** [comment]
Crosslinking:
- similar issue using wheels: https://github.com/mhammond/pywin32/issues/2038
- exe installers being deprecated #1939

**Comment by Avasam** [comment]
> Install pywin32 306 for Python 3.11 amd64 using (deprecated) installer
@andreygursky Are you able to replicate this using a wheel install? Support for the deprecated (exe) installers has been completely dropped.
