### ISSUE TITLE
situation where pywin32 crashes  whereas IDLE raises a RecursionError

### ISSUE THREAD

**Issue by scted** [mhammond/pywin32#2069]
The following buggy code causes pywin32 to crash whereas IDLE raises a RecursionError ... I don't know if the pywin32 behavior is intended or whether it would be preferrable to raise an Exception without crashing

```
PythonWin` 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32.
Portions Copyright 1994-2018 Mark Hammond - see 'Help/About PythonWin' for further copyright information.
>>> class x:
... 	a = 0
... 	

>>> class y:
... 	def __init__(self, bug=False):
... 		if not bug:
... 			self._xattr = x()
... 		else:
... 			#should set self._xattr but do not
... 			pass
... 	def __getattr__(self, attr):
... 		try:
... 			return getattr(self._xattr, attr)	#crashes pywin32 and raises RecursionError in Idle when bug
... 		except:
... 			raise
... 
>>> #works
>>> z=y(bug=False)
>>> z.a
0
>>> #crashes
>>> z=y(bug=True)
>>> z.                       #crashes as soon as '.' is typed
```

Here is the IDLE behvior (note using 3.10 instead of 3.11 here if that makes a difference)
```
Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
class x:
    a = 0

class y:
    def __init__(self, bug=False):
        if not bug:
            self._xattr = x()
        else:
            #should set self._xattr but do not
            pass
    def __getattr__(self, attr):
        try:
            return getattr(self._xattr, attr)   #crashes pywin32 and raises RecursionError in IDLE
        except AttributeError:
            raise

        
#works
        
z = y(bug=False)
z.a
0
#raises RecursionError
z = y(bug=True)
z.a
Traceback (most recent call last):
  File "<pyshell#37>", line 1, in <module>
    z.a
  File "<pyshell#31>", line 10, in __getattr__
    return getattr(self._xattr, attr)   #crashes pywin32 and raises RecursionError in IDLE
  File "<pyshell#31>", line 10, in __getattr__
    return getattr(self._xattr, attr)   #crashes pywin32 and raises RecursionError in IDLE
  File "<pyshell#31>", line 10, in __getattr__
    return getattr(self._xattr, attr)   #crashes pywin32 and raises RecursionError in IDLE
  [Previous line repeated 1022 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by Avasam** [comment]
To make it easier to replicate the breaking code, simply copy this to a file, open it in your IDE fo choice (Pythonwin for the crash) and run it:
```py
class x:
    a = 0

class y:
    def __init__(self, bug=False):
        if not bug:
            self._xattr = x()
        else:
            #should set self._xattr but do not
            pass
    def __getattr__(self, attr):
        try:
            return getattr(self._xattr, attr)   #crashes pywin32 and raises RecursionError in IDLE
        except AttributeError:
            raise

        
#works
        
z = y(bug=False)
z.a
0
#raises RecursionError
z = y(bug=True)
z.a
```
