### ISSUE TITLE
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024809), None)

### ISSUE THREAD

**Issue by mominurr** [mhammond/pywin32#2129]
Traceback (most recent call last):
  File "D:\Web Scraping Project\excel_to_pdf\excel_to_pdf.py", line 105, in convert_sheet_to_pdf
  File "<COMObject <unknown>>", line 3, in ExportAsFixedFormat
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2147024809), None)

**Comment by mhammond** [comment]
See https://github.com/mhammond/pywin32#support
