### ISSUE TITLE
Pywin32gui doesn't install

### ISSUE THREAD

**Issue by dougransom** [mhammond/pywin32#2239]
For all bugs, please provide the following information:

## Steps to reproduce the problem

`pip install win32gui`  breaks.
The sourceforge site for win32gui directs users to this github page.

Is there an API within pywin32 that subsumes win32gui?

`(venv) c:\Users\doug\code\dt>pip install win32gui
WARNING: Ignoring invalid distribution -atlink (c:\users\doug\appdata\local\programs\natlink_vert\environment\dns\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -atlink (c:\users\doug\appdata\local\programs\natlink_vert\environment\dns\venv\lib\site-packages)
Collecting win32gui
  Using cached win32gui-221.5.tar.gz (605 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "C:\Users\doug\AppData\Local\Programs\natlink_vert\environment\DNS\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\doug\AppData\Local\Programs\natlink_vert\environment\DNS\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\doug\AppData\Local\Programs\natlink_vert\environment\DNS\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\doug\AppData\Local\Temp\pip-build-env-2941zx89\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\doug\AppData\Local\Temp\pip-build-env-2941zx89\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\doug\AppData\Local\Temp\pip-build-env-2941zx89\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\doug\AppData\Local\Temp\pip-build-env-2941zx89\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 27, in <module>
        File "C:\Users\doug\AppData\Local\Temp\pip-install-5fdquhs4\win32gui_650699f152794c4eb1e8cc0158530d15\win32\distutils\gui.py", line 6, in <module>
          from .command import win32_build_ext
      ModuleNotFoundError: No module named 'win32.distutils.command'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: Ignoring invalid distribution -atlink (c:\users\doug\appdata\local\programs\natlink_vert\environment\dns\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -atlink (c:\users\doug\appdata\local\programs\natlink_vert\environment\dns\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -atlink (c:\users\doug\appdata\local\programs\natlink_vert\environment\dns\venv\lib\site-packages)

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
`

1. ...
2. ...
3. ...

```python

```

## System information

Python version and distribution:

pywin32 version:
3.10.3 32 bit.

Installed from PyPI or exe installer:
pypi.

Windows Version:

Microsoft Windows [Version 10.0.22631.3374]

DLL locations:

**Comment by dougransom** [comment]
Pywin32gui is subsubmed by this.  Might be an idea to inidicate on pypi pywin32gui is obsolete.

**Comment by mhammond** [comment]
I never knew pywin32gui existed and it wasn't uploaded by me!
