### ISSUE TITLE
Can't find pywintypes in virtual environment

### ISSUE THREAD

**Issue by nhunter77018** [mhammond/pywin32#2308]
## Steps to reproduce the problem
Simple program to read system keywords from a jpg file.
```
import pythoncom
from win32com.propsys import propsys
from win32com.shell import shellcon
import sys

def readTags(imgf_path):

    # get PROPERTYKEY for "System.Keywords"
    pk = propsys.PSGetPropertyKeyFromName("System.Keywords")

    # get property store for a given shell item (here a file)
    ps = propsys.SHGetPropertyStoreFromParsingName(imgf_path, None, shellcon.GPS_READWRITE, propsys.IID_IPropertyStore)

    # read & print existing (or not) property value, System.Keywords type is an array of string
    keywords = ps.GetValue(pk).GetValue()

    return keywords

if __name__ == '__main__':
        print(readTags(sys.argv[1]))
```
Works great!

> C:\Users\user\source\repos\Test>python test.py "D:\FaceDb\Friends\images\friends (1).jpg"
> ['Friends', 'Matt LeBlanc', 'Jennifer Aniston']
> 

Create & activate virtual environment.

> C:\Users\user\source\repos\Test>python -m venv .\env
> 
> C:\Users\user\source\repos\Test>env\Scripts\activate.bat
> 

Fails.

> (env) C:\Users\user\source\repos\Test>python test.py "D:\FaceDb\Friends\images\friends (1).jpg"
> Traceback (most recent call last):
>   File "C:\Users\user\source\repos\Test\test.py", line 1, in <module>
>     import pythoncom
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pythoncom.py", line 2, in <module>
>     import pywintypes
> ModuleNotFoundError: No module named 'pywintypes'

Deactivate virtual environment, all is good.

> (env) C:\Users\user\source\repos\Test>env\Scripts\deactivate.bat
> C:\Users\user\source\repos\Test>python test.py "D:\FaceDb\Friends\images\friends (1).jpg"
> ['Friends', 'Matt LeBlanc', 'Jennifer Aniston']
> 

Python version and distribution:
> Python 3.11.8

pywin32 version:
> 306?
> C:\Users\user\source\repos\Test>pip3 install pywin32
> Requirement already satisfied: pywin32 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (306)

Installed from PyPI or exe installer:
> PyPI

Windows Version:
> Windows 10 Home Version 22H2

DLL locations:
> C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pywin32_system32\pywintypes311.dll
> C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pywin32_system32\pythoncom311.dll

**Comment by Avasam** [comment]
Did you install pywin32 in your virtual environment and are you sure you are using python from your venv?
I'm asking because
> C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pythoncom.py
> c:\users\user\appdata\local\programs\python\python311\lib\site-packages
> C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pywin32_system32\pywintypes311.dll
> C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\pywin32_system32\pythoncom311.dll

Don't look like paths to your `./env` venv

**Comment by nhunter77018** [comment]
Hi, Avasam, thanks for your speedy response.
When I couldn't get it to work, I tried installing pywin32 in my virtual environment using pip like this.
> (env) pip3 install pywin32
> Requirement already satisfied: pywin32 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (306)
What is it I need to do?

**Comment by Seedmanc** [comment]
I'm also getting module 'win32com.propsys' has no attribute 'PSGetPropertyKeyFromName' and module 'win32com.shell.shell' has no attribute 'SHGetPropertyStoreFromParsingName'
