### ISSUE TITLE
MFC Object has died ... using sqlalchemy

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#657]
2013-08-10 02:11:06,780 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
I receive the following warning when using sqlalchemy with the engine.echo=True

There is indication of this same bug on the web circa 2007 but nothing recent that I have found to help me fix the problem.  

It is not a showstopper but it is annoying.

PS. PythonWin is awesome. I've used it for years and have never seen anything close to a bug.

 Traceback (most recent call last):
  File "C:\Python27\lib\logging\__init__.py", line 854, in emit
    getattr(stream, 'encoding', None)):
  File "C:\Python27\Lib\site-packages\pythonwin\pywin\mfc\object.py", line 23, in __getattr__
    raise win32ui.error("The MFC object has died.")
error: The MFC object has died.
Logged from file log.py, line 111
2013-08-10 02:11:06,828 INFO sqlalchemy.engine.base.Engine ()
MyTableau

Reported by: scted

Original Ticket: [pywin32/bugs/657](https://sourceforge.net/p/pywin32/bugs/657)

**Comment by Avasam** [comment]
Missing MRE, cannot replicate. User can't be pinged du to being a sourceforge migrated issue.

Hard to say what's the cause of the issue originally. If someone has a similar issue it's better to just open a new one will all the required information.
