### ISSUE TITLE
In Word, BuiltInDocumentProperties raises 'Does not support a collection.' error

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#703]
The BuiltInDocumentProperties collection cannot be accessed nor with __call__ nor with __getitem__.
Converting to list does not work neither. Only iteration works.

With doc being a Word Document:
        print doc.BuiltInDocumentProperties
        print [d for d in doc.BuiltInDocumentProperties]
        print doc.BuiltInDocumentProperties(1)
gives
<win32com.gen_py.Microsoft Office 9.0 Object Library.DocumentProperties instance at 0x72132648>
[<win32com.gen_py.Microsoft Office 9.0 Object Library.DocumentProperty instance at 0x72132768>,
...,
<win32com.gen_py.Microsoft Office 9.0 Object Library.DocumentProperty instance at 0x72134048>, <win32com.gen_py.Microsoft Office 9.0 Object Library.DocumentProperty instance at 0x72134088>]
Traceback (most recent call last):
  File "C:/Documents and Settings/gfj138/My Documents/PycharmProjects/GOOD_repo/good/yap/offer_generator.py", line 266, in <module>
    generate_all_texts()
  File "C:/Documents and Settings/gfj138/My Documents/PycharmProjects/GOOD_repo/good/yap/offer_generator.py", line 240, in generate_all_texts
    doc = generate_offer(wb)
  File "C:/Documents and Settings/gfj138/My Documents/PycharmProjects/GOOD_repo/good/yap/offer_generator.py", line 47, in generate_offer
    print doc.BuiltInDocumentProperties(1)
AttributeError: DocumentProperties instance has no __call__ method

On a DocumentProperty, nor the Name nor the Value attribute works
        print [d.Name for d in doc.BuiltInDocumentProperties]
gives
Traceback (most recent call last):
  File "C:/Documents and Settings/gfj138/My Documents/PycharmProjects/GOOD_repo/good/yap/offer_generator.py", line 266, in <module>
    generate_all_texts()
  File "C:/Documents and Settings/gfj138/My Documents/PycharmProjects/GOOD_repo/good/yap/offer_generator.py", line 240, in generate_all_texts
    doc = generate_offer(wb)
  File "C:/Documents and Settings/gfj138/My Documents/PycharmProjects/GOOD_repo/good/yap/offer_generator.py", line 46, in generate_offer
    print [d.Name for d in doc.BuiltInDocumentProperties]
  File "C:\Program Files\Anaconda\envs\good\lib\site-packages\win32com\client\__init__.py", line 465, in __getattr__
    raise AttributeError("'%s' object has no attribute '%s'" % (repr(self), attr))
AttributeError: '<win32com.gen_py.Microsoft Office 9.0 Object Library.DocumentProperty instance at 0x72087712>' object has no attribute 'Name'

Reported by: sdementen

Original Ticket: [pywin32/bugs/703](https://sourceforge.net/p/pywin32/bugs/703)

**Comment by Avasam** [comment]
I couldn't replicate with Word 16 / 2019. Either this is an old Word issue, or is already fixed in pywin32 308:

```py
import win32com.client.dynamic

word = win32com.client.dynamic.Dispatch("Word.Application")
word.Documents.Add()
print(doc.BuiltInDocumentProperties)
print([d for d in doc.BuiltInDocumentProperties])
print(repr(doc.BuiltInDocumentProperties(1)))
```
