### ISSUE TITLE
pywin32-64 fails to install on Win 7-64/Py 3.5-64

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#706]
I just did a clean install of Python 3.5 64-bit into Windows 7 64-bit SP1.
I then installed pywin32. In both cases I used Admin privileges.

Unfortunately, at the end of the pywin32 install I got this error message displayed in the installer window:

Traceback (most recent call last):
  File "<string>", line 613, in <module>
  File "<string>", line 321, in install
  File "<string>", line 159, in LoadSystemModule
  File "C:\Program Files\Python 3.5\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 903, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

The packages I used:
python-3.5.0-amd64.exe
pywin32-219.win-amd64-py3.5.exe

Reported by: m_n_summerfield

Original Ticket: [pywin32/bugs/706](https://sourceforge.net/p/pywin32/bugs/706)

**Comment by Avasam** [comment]
[.exe/binary installers are now deprecated](https://github.com/mhammond/pywin32#binaries) and wheels for all bitness are available on PyPI
This issue should also be fixed in pywin32>=220
