### ISSUE TITLE
Python 3: can't import pip in PythonWin

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#722]
I have ActiveState Python 3.4.3.2 (64-bit) installed.

From the PythonWin console:

>>> import pip
Traceback (most recent call last):
  File "<interactive input>", line 1, in <module>
  File "C:\Python34\lib\site-packages\pip\__init__.py", line 9, in <module>
    from pip.log import logger
  File "C:\Python34\lib\site-packages\pip\log.py", line 8, in <module>
    from pip import backwardcompat
  File "C:\Python34\lib\site-packages\pip\backwardcompat\__init__.py", line 27, in <module>
    console_encoding = sys.__stdout__.encoding
AttributeError: 'NoneType' object has no attribute 'encoding'

Reported by: nickjacobson

Original Ticket: [pywin32/bugs/722](https://sourceforge.net/p/pywin32/bugs/722)

**Comment by Avasam** [comment]
Since the issue happened in pip, this either was a pip issue, or pywin32 somehow set `sys.stdout` to `None`, but this seems to be currently resolved
![image](https://github.com/mhammond/pywin32/assets/1350584/76bba70f-5659-48d5-9c80-4a80707179a8)
```python
>>> import pip
>>> import sys
>>> sys.stdout
<pywin.framework.interact.InteractiveView object at 0x000002B030C4E310>
```
