### ISSUE TITLE
OverflowError in the debugger

### ISSUE THREAD

**Issue by xoviat** [mhammond/pywin32#727]
While trying to debug a program with pythonwin 220 I get **OverflowError** in the debugger:

`
PythonWin 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32.
Portions Copyright 1994-2008 Mark Hammond - see 'Help/About PythonWin' for further copyright information.
Traceback (most recent call last):
  File "C:\ProgramData\chocolatey\lib\python3\tools\Lib\site-packages\Pythonwin\pywin\framework\scriptutils.py", line 321, in RunScript
    debugger.run(codeObject, __main__.__dict__, start_stepping=1)
  File "C:\ProgramData\chocolatey\lib\python3\tools\Lib\site-packages\Pythonwin\pywin\debugger\__init__.py", line 60, in run
    _GetCurrentDebugger().run(cmd, globals,locals, start_stepping)
  File "C:\ProgramData\chocolatey\lib\python3\tools\Lib\site-packages\Pythonwin\pywin\debugger\debugger.py", line 654, in run
    exec(cmd, globals, locals)
  File "C:\Work\opencv-py\read_tiff.py", line 1, in <module>
    from PIL import Image
  File "C:\Work\opencv-py\read_tiff.py", line 1, in <module>
    from PIL import Image
  File "C:\ProgramData\chocolatey\lib\python3\tools\lib\bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "C:\ProgramData\chocolatey\lib\python3\tools\lib\bdb.py", line 66, in dispatch_line
    self.user_line(frame)
  File "C:\ProgramData\chocolatey\lib\python3\tools\Lib\site-packages\Pythonwin\pywin\debugger\debugger.py", line 616, in user_line
    debugger_parent.user_line(self, frame)
  File "C:\ProgramData\chocolatey\lib\python3\tools\lib\pdb.py", line 259, in user_line
    self.interaction(frame, None)
  File "C:\ProgramData\chocolatey\lib\python3\tools\lib\pdb.py", line 346, in interaction
    self._cmdloop()
  File "C:\ProgramData\chocolatey\lib\python3\tools\lib\pdb.py", line 319, in _cmdloop
    self.cmdloop()
  File "C:\ProgramData\chocolatey\lib\python3\tools\Lib\site-packages\Pythonwin\pywin\debugger\debugger.py", line 575, in cmdloop
    self.GUIAboutToBreak()
  File "C:\ProgramData\chocolatey\lib\python3\tools\Lib\site-packages\Pythonwin\pywin\debugger\debugger.py", line 847, in GUIAboutToBreak
    self.GUIAboutToInteract()
  File "C:\ProgramData\chocolatey\lib\python3\tools\Lib\site-packages\Pythonwin\pywin\debugger\debugger.py", line 878, in GUIAboutToInteract
    self.GUIRespondDebuggerData()
  File "C:\ProgramData\chocolatey\lib\python3\tools\Lib\site-packages\Pythonwin\pywin\debugger\debugger.py", line 833, in GUIRespondDebuggerData
    cb.RespondDebuggerData()
  File "C:\ProgramData\chocolatey\lib\python3\tools\Lib\site-packages\Pythonwin\pywin\debugger\debugger.py", line 219, in RespondDebuggerData
    if self.list.GetItemImage(handle)!= (col, selCol):
OverflowError: Python int too large to convert to C long
>>>
`

Reported by: dbely

Original Ticket: [pywin32/bugs/727](https://sourceforge.net/p/pywin32/bugs/727)

**Comment by mhammond** [comment]
Fixed in #375dca3f
