### ISSUE TITLE
No Module named 'pywintypes'

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#755]
Here is the output when I try to run a script:

Traceback (most recent call last):
  File "C:\Users\foo\Python\Python35\outlooktest.py", line 1, in <module>
    from win32com.client import Dispatch, GetObject
  File "C:\Users\foo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\win32com\__init__.py", line 7, in <module>
    import pythoncom
  File "C:\Users\foo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
ModuleNotFoundError: No module named 'pywintypes'

Package was instralled from pypi through pip.

Also had to modify the init script for win32com by changing the line import win32pi, sys, os to two lines:

from win32 import win32api
import sys, os

Reported by: jbarker2160

Original Ticket: [pywin32/bugs/755](https://sourceforge.net/p/pywin32/bugs/755)

**Comment by simryang** [comment]
> Sadly installing via pip has issues due to the fact it doesn't run the postinstall script. You could try manually running "python pywin32_postinstall.py -install"
> 
> Original comment by: mhammond

I executed that command successfully and still same errors occurs.

**Comment by GEOJOEco** [comment]
I have an amd64 bit and I'm having the same issue.

**Comment by Avasam** [comment]
@jbarker2160 @GEOJOEco Can you confirm if you still have this issue specifically on the most recent version of pywin32 (306 as of writing this comment), on Python >= 3.8, installing from pip ? As well as an updated traceback log if you get one.

**Comment by Avasam** [comment]
@simryang
